{
  "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
  "repository_url": "https://api.github.com/repos/NomicFoundation/hardhat",
  "labels_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672/labels{/name}",
  "comments_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672/comments",
  "events_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672/events",
  "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672",
  "id": 1227453780,
  "node_id": "I_kwDOB7jojM5JKXVU",
  "number": 2672,
  "title": "TransactionExecutionError: Headers Timeout Error",
  "user": {
    "login": "Pzixel",
    "id": 11201122,
    "node_id": "MDQ6VXNlcjExMjAxMTIy",
    "avatar_url": "https://avatars.githubusercontent.com/u/11201122?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Pzixel",
    "html_url": "https://github.com/Pzixel",
    "followers_url": "https://api.github.com/users/Pzixel/followers",
    "following_url": "https://api.github.com/users/Pzixel/following{/other_user}",
    "gists_url": "https://api.github.com/users/Pzixel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Pzixel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Pzixel/subscriptions",
    "organizations_url": "https://api.github.com/users/Pzixel/orgs",
    "repos_url": "https://api.github.com/users/Pzixel/repos",
    "events_url": "https://api.github.com/users/Pzixel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Pzixel/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": true,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 33,
  "created_at": "2022-05-06T06:03:24Z",
  "updated_at": "2023-03-29T00:15:39Z",
  "closed_at": "2022-12-28T09:31:45Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": "resolved",
  "body": "## Bug Description\r\n\r\nWhen running long tests on harhat network all transactions start failing and then it stalls. \r\n\r\n## Reproducible By\r\n\r\nThis snippet should do the trick:\r\n\r\n```ts\r\nfor (let j = 0; j < 1000000; j++) {\r\n    const amountIn = '1000';\r\n    const [signer1] = await ethers.getSigners();\r\n    const swapRouter = ISwapRouter__factory.connect('0xE592427A0AEce92De3Edee1F18E0157C05861564', signer1);\r\n    const recipient = signer1.address;\r\n    await waitEthersTx(swapRouter.exactInput({\r\n        // WETH -> USDC 3000 fee\r\n        path: \"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2000bb8A0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48\",\r\n        amountIn: amountIn,\r\n        deadline: constants.MaxUint256,\r\n        recipient,\r\n        amountOutMinimum: 1,\r\n    }, {\r\n        value: amountIn,\r\n    }));\r\n}\r\n```\r\n\r\n## Expected Behavior\r\n\r\nIt should be working without issues\r\n\r\n## Logs & Screenshots\r\n\r\nTransaction fails with\r\n\r\n```ts\r\nTransactionExecutionError: Headers Timeout Error\r\n    at HardhatNode.mineBlock (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:478:15)\r\n    at async EthModule._sendTransactionAndReturnHash (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)\r\n    at async HardhatNetworkProvider.request (/Users/pzixel/Documents/Repos/test/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)\r\n    at async EthersProviderWrapper.send (/Users/pzixel/Documents/Repos/test/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)\r\n\r\n    Caused by: HeadersTimeoutError: Headers Timeout Error\r\n        at Timeout.onParserTimeout [as _onTimeout] (/Users/pzixel/Documents/Repos/test/node_modules/undici/lib/client.js:1005:28)\r\n        at listOnTimeout (node:internal/timers:561:11)\r\n        at processTimers (node:internal/timers:502:7)\r\n```\r\n\r\n## Environment\r\n\r\nNode 16.5.0, Macos 12.3.1 M1 Pro (but I'm pretty sure it's doesn't matter)\r\n\r\nHardhat config if relevant:\r\n\r\n```ts\r\nconst networks: NetworksUserConfig = {\r\n    hardhat: {\r\n        forking: {\r\n            url: myurl,\r\n        },\r\n        chainId: 1,\r\n    },\r\n};\r\n```",
  "closed_by": {
    "login": "fvictorio",
    "id": 417134,
    "node_id": "MDQ6VXNlcjQxNzEzNA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/417134?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fvictorio",
    "html_url": "https://github.com/fvictorio",
    "followers_url": "https://api.github.com/users/fvictorio/followers",
    "following_url": "https://api.github.com/users/fvictorio/following{/other_user}",
    "gists_url": "https://api.github.com/users/fvictorio/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fvictorio/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fvictorio/subscriptions",
    "organizations_url": "https://api.github.com/users/fvictorio/orgs",
    "repos_url": "https://api.github.com/users/fvictorio/repos",
    "events_url": "https://api.github.com/users/fvictorio/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fvictorio/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672/timeline",
  "performed_via_github_app": null,
  "state_reason": "not_planned"
}
[
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1119286283",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1119286283",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1119286283,
    "node_id": "IC_kwDOB7jojM5CtvQL",
    "user": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2022-05-06T06:03:48Z",
    "updated_at": "2022-05-06T06:03:48Z",
    "author_association": "CONTRIBUTOR",
    "body": "This issue is also being [tracked on Linear](https://linear.app/nomic-foundation/issue/HH-602/transactionexecutionerror-headers-timeout-error).\n\nWe use Linear to manage our development process, but we keep the conversations on Github.\n\nLINEAR-ID: d203952e-41c3-4764-a380-1abb7cff8d1e",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1119286283/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1126368047",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1126368047",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1126368047,
    "node_id": "IC_kwDOB7jojM5DIwMv",
    "user": {
      "login": "feuGeneA",
      "id": 7883777,
      "node_id": "MDQ6VXNlcjc4ODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7883777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feuGeneA",
      "html_url": "https://github.com/feuGeneA",
      "followers_url": "https://api.github.com/users/feuGeneA/followers",
      "following_url": "https://api.github.com/users/feuGeneA/following{/other_user}",
      "gists_url": "https://api.github.com/users/feuGeneA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feuGeneA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feuGeneA/subscriptions",
      "organizations_url": "https://api.github.com/users/feuGeneA/orgs",
      "repos_url": "https://api.github.com/users/feuGeneA/repos",
      "events_url": "https://api.github.com/users/feuGeneA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feuGeneA/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-13T19:16:05Z",
    "updated_at": "2022-05-13T19:16:05Z",
    "author_association": "CONTRIBUTOR",
    "body": "Thank you for using Hardhat. Can you provide a more complete reproduction scenario? Perhaps in a separate repo or in an attachment? Something I can easily just run. Thanks.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1126368047/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1130081168",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1130081168",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1130081168,
    "node_id": "IC_kwDOB7jojM5DW6uQ",
    "user": {
      "login": "DecentraSol",
      "id": 283618,
      "node_id": "MDQ6VXNlcjI4MzYxOA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/283618?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DecentraSol",
      "html_url": "https://github.com/DecentraSol",
      "followers_url": "https://api.github.com/users/DecentraSol/followers",
      "following_url": "https://api.github.com/users/DecentraSol/following{/other_user}",
      "gists_url": "https://api.github.com/users/DecentraSol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DecentraSol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DecentraSol/subscriptions",
      "organizations_url": "https://api.github.com/users/DecentraSol/orgs",
      "repos_url": "https://api.github.com/users/DecentraSol/repos",
      "events_url": "https://api.github.com/users/DecentraSol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DecentraSol/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-18T14:20:38Z",
    "updated_at": "2022-05-18T14:20:38Z",
    "author_association": "NONE",
    "body": "I also have this issue. I tried upgradeProxy with an impersonated instance of the proxy contract to be upgraded. \r\nIt's not really long running but quite some work to upgrade an upgradable contract.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1130081168/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1133597366",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1133597366",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1133597366,
    "node_id": "IC_kwDOB7jojM5DkVK2",
    "user": {
      "login": "therawk",
      "id": 24702753,
      "node_id": "MDQ6VXNlcjI0NzAyNzUz",
      "avatar_url": "https://avatars.githubusercontent.com/u/24702753?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/therawk",
      "html_url": "https://github.com/therawk",
      "followers_url": "https://api.github.com/users/therawk/followers",
      "following_url": "https://api.github.com/users/therawk/following{/other_user}",
      "gists_url": "https://api.github.com/users/therawk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/therawk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/therawk/subscriptions",
      "organizations_url": "https://api.github.com/users/therawk/orgs",
      "repos_url": "https://api.github.com/users/therawk/repos",
      "events_url": "https://api.github.com/users/therawk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/therawk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-21T10:36:54Z",
    "updated_at": "2022-05-21T10:36:54Z",
    "author_association": "NONE",
    "body": "I'm struggling with this, too. I call a function on a smart contract which takes a while to finish and get this error:\r\n\r\n```\r\nHeadersTimeoutError: Headers Timeout Error\r\n    at Timeout.onParserTimeout [as _onTimeout] (/dev/collab/node_modules/undici/lib/client.js:1005:28)\r\n    at listOnTimeout (node:internal/timers:559:11)\r\n    at processTimers (node:internal/timers:500:7) {\r\n  code: 'UND_ERR_HEADERS_TIMEOUT'\r\n}\r\n```\r\nWhat exactly is causing this Timeout Error? I'm using mainnet fork via Alchemy. Is this timeout caused by Alchemy, Hardhat or the undici lib? ",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1133597366/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1133602816",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1133602816",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1133602816,
    "node_id": "IC_kwDOB7jojM5DkWgA",
    "user": {
      "login": "Pzixel",
      "id": 11201122,
      "node_id": "MDQ6VXNlcjExMjAxMTIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/11201122?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Pzixel",
      "html_url": "https://github.com/Pzixel",
      "followers_url": "https://api.github.com/users/Pzixel/followers",
      "following_url": "https://api.github.com/users/Pzixel/following{/other_user}",
      "gists_url": "https://api.github.com/users/Pzixel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Pzixel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Pzixel/subscriptions",
      "organizations_url": "https://api.github.com/users/Pzixel/orgs",
      "repos_url": "https://api.github.com/users/Pzixel/repos",
      "events_url": "https://api.github.com/users/Pzixel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Pzixel/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-21T11:20:55Z",
    "updated_at": "2022-05-21T11:21:47Z",
    "author_association": "CONTRIBUTOR",
    "body": "I've got it on two different endpoints (non-alchemy ones) so this must be a hardhat issue.\r\n\r\nI might try creating a MRE but I will only be able to do so in 2 weeks or so. I hope someone comes with better example earlier.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1133602816/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1134299173",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1134299173",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1134299173,
    "node_id": "IC_kwDOB7jojM5DnAgl",
    "user": {
      "login": "DecentraSol",
      "id": 283618,
      "node_id": "MDQ6VXNlcjI4MzYxOA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/283618?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DecentraSol",
      "html_url": "https://github.com/DecentraSol",
      "followers_url": "https://api.github.com/users/DecentraSol/followers",
      "following_url": "https://api.github.com/users/DecentraSol/following{/other_user}",
      "gists_url": "https://api.github.com/users/DecentraSol/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DecentraSol/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DecentraSol/subscriptions",
      "organizations_url": "https://api.github.com/users/DecentraSol/orgs",
      "repos_url": "https://api.github.com/users/DecentraSol/repos",
      "events_url": "https://api.github.com/users/DecentraSol/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DecentraSol/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-23T07:41:01Z",
    "updated_at": "2022-05-23T07:41:01Z",
    "author_association": "NONE",
    "body": "I only got it on a hardhat local node when I was forking from a Polygon mainnet via a public node. There might be a timeout when getting the data from the live node. If I repeat the command a couple of times it disappears. Obviously when all data are downloaded the the local node eventually.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1134299173/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1135078965",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1135078965",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1135078965,
    "node_id": "IC_kwDOB7jojM5Dp-41",
    "user": {
      "login": "feuGeneA",
      "id": 7883777,
      "node_id": "MDQ6VXNlcjc4ODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7883777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feuGeneA",
      "html_url": "https://github.com/feuGeneA",
      "followers_url": "https://api.github.com/users/feuGeneA/followers",
      "following_url": "https://api.github.com/users/feuGeneA/following{/other_user}",
      "gists_url": "https://api.github.com/users/feuGeneA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feuGeneA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feuGeneA/subscriptions",
      "organizations_url": "https://api.github.com/users/feuGeneA/orgs",
      "repos_url": "https://api.github.com/users/feuGeneA/repos",
      "events_url": "https://api.github.com/users/feuGeneA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feuGeneA/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-23T19:53:13Z",
    "updated_at": "2022-05-23T19:53:13Z",
    "author_association": "CONTRIBUTOR",
    "body": "I'm closing this because it sounds like Hardhat is behaving as expected.\r\n\r\nThis error message is simply the result of a network timeout, and the mere presence of this message does not indicate a problem with Hardhat, and GitHub Issues are intended to be used exclusively for problems in Hardhat itself.\r\n\r\nThere are many reasons why such a timeout may occur, including a problem on the endpoint (eg public node). It could also be the case that the computation you're requesting the node to execute may simply be a longer-running computation than the timeout values that have been configured at various points in the networking stack (both on the client and on the server).\r\n\r\nIf anyone suspects a problem that actually lies within Hardhat, please feel free to re-open this Issue, and, ideally, provide a minimal, reproducible example.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1135078965/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1136648099",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1136648099",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1136648099,
    "node_id": "IC_kwDOB7jojM5Dv9-j",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T02:26:55Z",
    "updated_at": "2022-05-25T02:26:55Z",
    "author_association": "NONE",
    "body": "i am also seeing this when forking an ethereum node",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1136648099/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137766287",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137766287",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137766287,
    "node_id": "IC_kwDOB7jojM5D0O-P",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T19:27:21Z",
    "updated_at": "2022-05-25T19:27:21Z",
    "author_association": "NONE",
    "body": "I'm also seeing it forking an ethereum archive node of mainnet. :/",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137766287/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137769815",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137769815",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137769815,
    "node_id": "IC_kwDOB7jojM5D0P1X",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T19:31:42Z",
    "updated_at": "2022-05-25T19:34:08Z",
    "author_association": "NONE",
    "body": "I've taken a pcap, 100% of the RPC calls were responded to. There was one call that looked like it took 1 second to respond.\r\n\r\n## Here is each request and the latency of the request.\r\n![hardhat-network-for-test-run](https://user-images.githubusercontent.com/787344/170352524-f24b1284-f641-4bf3-99e9-14deba68fcf8.png)\r\n \r\n## RPC HTTP Status codes\r\n<img width=\"912\" alt=\"image\" src=\"https://user-images.githubusercontent.com/787344/170352951-d0b104f1-369a-4ae0-b029-e9e21f56a050.png\">\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137769815/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137772060",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137772060",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137772060,
    "node_id": "IC_kwDOB7jojM5D0QYc",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T19:34:28Z",
    "updated_at": "2022-05-25T19:35:03Z",
    "author_association": "NONE",
    "body": "I'm not seeing any timeouts on the wire or from the server, of which I'm the only client using.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137772060/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137811571",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137811571",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137811571,
    "node_id": "IC_kwDOB7jojM5D0aBz",
    "user": {
      "login": "therawk",
      "id": 24702753,
      "node_id": "MDQ6VXNlcjI0NzAyNzUz",
      "avatar_url": "https://avatars.githubusercontent.com/u/24702753?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/therawk",
      "html_url": "https://github.com/therawk",
      "followers_url": "https://api.github.com/users/therawk/followers",
      "following_url": "https://api.github.com/users/therawk/following{/other_user}",
      "gists_url": "https://api.github.com/users/therawk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/therawk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/therawk/subscriptions",
      "organizations_url": "https://api.github.com/users/therawk/orgs",
      "repos_url": "https://api.github.com/users/therawk/repos",
      "events_url": "https://api.github.com/users/therawk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/therawk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T20:21:05Z",
    "updated_at": "2022-05-25T20:21:05Z",
    "author_association": "NONE",
    "body": "Would you be interested in a repo I'm having this issue with?",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137811571/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137817385",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137817385",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137817385,
    "node_id": "IC_kwDOB7jojM5D0bcp",
    "user": {
      "login": "feuGeneA",
      "id": 7883777,
      "node_id": "MDQ6VXNlcjc4ODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7883777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feuGeneA",
      "html_url": "https://github.com/feuGeneA",
      "followers_url": "https://api.github.com/users/feuGeneA/followers",
      "following_url": "https://api.github.com/users/feuGeneA/following{/other_user}",
      "gists_url": "https://api.github.com/users/feuGeneA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feuGeneA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feuGeneA/subscriptions",
      "organizations_url": "https://api.github.com/users/feuGeneA/orgs",
      "repos_url": "https://api.github.com/users/feuGeneA/repos",
      "events_url": "https://api.github.com/users/feuGeneA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feuGeneA/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T20:28:42Z",
    "updated_at": "2022-05-25T20:49:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "@bretep thank you for this. I've re-opened the issue. Clearly this isn't necessarily an issue connecting to the remote node. In particular, the presence of `HardhatNode.mineBlock()` in the call stack, which I hadn't noticed before your confirmation here, points a finger at Hardhat.\r\n\r\nAre you able to configure Wireshark to also capture loopback traffic? (I know that is easier on some systems than others.) That would capture this activity, if I'm understanding the scenario correctly.\r\n\r\nAlso, can you confirm that you have the same symptoms as in the original Issue description? In particular, I'm interested in hearing whether `HardhatNode.mineBlock()` appears in your call stack.\r\n\r\nFinally, would you happen to have a reproducible scenario for this? Even with all these wonderful clues, without a reproduction it will be difficult to even diagnose this, much less get it fixed.\r\n\r\nThanks again!",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137817385/reactions",
      "total_count": 2,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 2,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137853649",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1137853649",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1137853649,
    "node_id": "IC_kwDOB7jojM5D0kTR",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-25T21:13:16Z",
    "updated_at": "2022-05-25T21:13:16Z",
    "author_association": "NONE",
    "body": "> @bretep thank you for this. I've re-opened the issue. Clearly this isn't necessarily an issue connecting to the remote node. In particular, the presence of `HardhatNode.mineBlock()` in the call stack, which I hadn't noticed before your confirmation here, points a finger at Hardhat.\n> \n> \n> \n> Are you able to configure Wireshark to also capture loopback traffic? (I know that is easier on some systems than others.) That would capture this activity, if I'm understanding the scenario correctly.\n> \n> \n> \n> Also, can you confirm that you have the same symptoms as in the original Issue description? In particular, I'm interested in hearing whether `HardhatNode.mineBlock()` appears in your call stack.\n> \n> \n> \n> Finally, would you happen to have a reproducible scenario for this? Even with all these wonderful clues, without a reproduction it will be difficult to even diagnose this, much less get it fixed.\n> \n> \n> \n> Thanks again!\n\nYes, I can. I'll do that once I get back to my computer. It's going to be a few hours. ",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1137853649/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138105728",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1138105728",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1138105728,
    "node_id": "IC_kwDOB7jojM5D1h2A",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-26T03:18:13Z",
    "updated_at": "2022-05-26T03:18:13Z",
    "author_association": "NONE",
    "body": "Hi, I've captured the loopback device. I didn't see anything that took more than 0.5ms. \r\n\r\nI'll see what I can do about a reproducible scenario.\r\n\r\n![hardhat-network-for-test-run-lo](https://user-images.githubusercontent.com/787344/170408673-c340d9ae-14dc-4ef7-be20-75b0a0827d85.png)\r\n\r\n<img width=\"912\" alt=\"Screen Shot 2022-05-25 at 20 14 24\" src=\"https://user-images.githubusercontent.com/787344/170408698-55b05049-253f-4eeb-b4b5-598758de7e31.png\">\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138105728/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138109586",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1138109586",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1138109586,
    "node_id": "IC_kwDOB7jojM5D1iyS",
    "user": {
      "login": "bretep",
      "id": 787344,
      "node_id": "MDQ6VXNlcjc4NzM0NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/787344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bretep",
      "html_url": "https://github.com/bretep",
      "followers_url": "https://api.github.com/users/bretep/followers",
      "following_url": "https://api.github.com/users/bretep/following{/other_user}",
      "gists_url": "https://api.github.com/users/bretep/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bretep/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bretep/subscriptions",
      "organizations_url": "https://api.github.com/users/bretep/orgs",
      "repos_url": "https://api.github.com/users/bretep/repos",
      "events_url": "https://api.github.com/users/bretep/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bretep/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-26T03:25:45Z",
    "updated_at": "2022-05-26T03:25:45Z",
    "author_association": "NONE",
    "body": "hardhat v2.9.6\r\nSpecifically getting the following error:\r\n\r\n```\r\n     HeadersTimeoutError: Headers Timeout Error\r\n      at Timeout.onParserTimeout [as _onTimeout] (node_modules/undici/lib/client.js:1005:28)\r\n      at listOnTimeout (node:internal/timers:561:11)\r\n      at processTimers (node:internal/timers:502:7)\r\n\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138109586/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138182826",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1138182826",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1138182826,
    "node_id": "IC_kwDOB7jojM5D10qq",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-26T05:56:56Z",
    "updated_at": "2022-05-26T14:37:37Z",
    "author_association": "NONE",
    "body": "To lend some credence to the mined block thread while i work on a minimum viable, these are some of the errors that I see. While I do not see the same error, but it seems very similar: takes a long time to do anything / mine a block\r\n```\r\nMined block #14361014\r\n  Block: 0xd6005a46c9070513722990be5765c6f465178475e91be0e69c2b7c2ecbd50886\r\n    Base fee: 0\r\n    Transaction:           0xf5ba928fb13b3a7f0e5472d16497fd45914832e51d439f4701c006586dcd987e\r\n      Contract call:       Swap#uniswapV3ExactInputSingle\r\n      From:                0xf42b8cf17ad3bbc0a203b2d2b5e7be373650f456\r\n      To:                  0x9d634360c39aa1b9a75b013a66a137bb390924d5\r\n      Value:               0 ETH\r\n      Gas used:            9692216 of 10000000\r\n\r\n      Error: Transaction reverted without a reason string\r\n          at <UnrecognizedContract>.<unknown> (0xc2e9f25be6257c210d7adf0d4cd6e3e881ba25f8)\r\n          at <UnrecognizedContract>.<unknown> (0xe592427a0aece92de3edee1f18e0157c05861564)\r\n          at Swap.uniswapV3ExactInputSingle (contracts/Swap.sol:208)\r\n          at async HardhatNode._mineBlockWithPendingTxs (.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)\r\n          at async HardhatNode.mineBlock (.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)\r\n          at async HardhatModule._intervalMineAction (.../node_modules/hardhat/src/internal/hardhat-network/provider/modules/hardhat.ts:175:20)\r\n          at async HardhatNetworkProvider._sendWithLogging (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)\r\n          at async HardhatNetworkProvider.request (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)\r\n          at async MiningTimer._mineFunction (.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:325:9)\r\n          at async MiningTimer._loop (.../node_modules/hardhat/src/internal/hardhat-network/provider/MiningTimer.ts:98:5)\r\n```\r\nthis is a simple uniswapv3 swap, which should only cost <50k gas, but for whatever reason, it ends up costing near the hard coded gas limit provided by the client. this gas usage varies wildly but is almost always > 1m\r\n\r\nwhen i try to inspect the transaction using hardhat-tracer, i get this error\r\nhttps://github.com/zemse/hardhat-tracer/issues/16",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138182826/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 1
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138719129",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1138719129",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1138719129,
    "node_id": "IC_kwDOB7jojM5D33mZ",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-26T15:45:44Z",
    "updated_at": "2022-05-26T15:52:59Z",
    "author_association": "NONE",
    "body": "[minimal.zip](https://github.com/NomicFoundation/hardhat/files/8780230/minimal.zip)\r\ni attempted to create a minimal example - did not quite get all the way to the originally mentioned header error, but got to the one i posted above.\r\n```bash\r\nyarn\r\nyarn run compile\r\nyarn run fork # separate terminal to view logs\r\nyarn run start\r\n```\r\n\r\nit should stop after mining the 3rd tx and hit the failure with the high gas consumption on the 4th - after stalling for a couple minutes\r\n\r\n#1 deploy\r\n#2 approve\r\n#3 deposit weth\r\n#4 swap - odd failure\r\n\r\nto see the 0x0 error one has to add their transaction hash to the following command:\r\n```bash\r\nnode_modules/.bin/hardhat --network hardhat trace --hash 0x99e005a537c5e8639c0cf75db734c78504fc53005895b8decfe7e5ae4ab4f3b9 --rpc http://localhost:8545\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1138719129/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 1,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1139795595",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1139795595",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1139795595,
    "node_id": "IC_kwDOB7jojM5D7-aL",
    "user": {
      "login": "feuGeneA",
      "id": 7883777,
      "node_id": "MDQ6VXNlcjc4ODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7883777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feuGeneA",
      "html_url": "https://github.com/feuGeneA",
      "followers_url": "https://api.github.com/users/feuGeneA/followers",
      "following_url": "https://api.github.com/users/feuGeneA/following{/other_user}",
      "gists_url": "https://api.github.com/users/feuGeneA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feuGeneA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feuGeneA/subscriptions",
      "organizations_url": "https://api.github.com/users/feuGeneA/orgs",
      "repos_url": "https://api.github.com/users/feuGeneA/repos",
      "events_url": "https://api.github.com/users/feuGeneA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feuGeneA/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-27T16:53:12Z",
    "updated_at": "2022-05-27T16:53:12Z",
    "author_association": "CONTRIBUTOR",
    "body": "This Issue has been added to the team's backlog. Thanks @3commascapital for your help on this repro!",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1139795595/reactions",
      "total_count": 3,
      "+1": 3,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1141190119",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1141190119",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1141190119,
    "node_id": "IC_kwDOB7jojM5EBS3n",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-05-30T13:56:46Z",
    "updated_at": "2022-05-30T13:56:46Z",
    "author_association": "NONE",
    "body": "also, just some extra information, it looks like, both the hardhat fork as well as the polling side get \"stuck\", as in when one is polling for a transaction hash, the requests return just fine the first couple of rounds, but often on the 3rd check (on a ~1s poll interval and a 3s block time) the response for `eth_getTransactionReceipt` freezes as well - is there an internal db that is locking transaction receipts there which could offer a clue?",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1141190119/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1163498468",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1163498468",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1163498468,
    "node_id": "IC_kwDOB7jojM5FWZPk",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-06-22T19:03:39Z",
    "updated_at": "2022-06-22T19:03:39Z",
    "author_association": "NONE",
    "body": "not sure if it's the same issue, but i also got this error recently\r\n```\r\nhardhat_intervalMine\r\n\r\nUnexpected error calling hardhat_intervalMine: TransactionExecutionError: the tx doesn't have the correct nonce. account has nonce of: 31 tx has nonce of: 27 (vm hf=arrowGlacier -> block number=14361621 hash=0x5f9b8d32f78e2086dacb20d46304b4454311de11312a92a108a977bdcf0df80a hf=arrowGlacier baseFeePerGas=0 txs=0 uncles=0 -> tx type=0 hash=0x8c9b94664842afe482f39bff752c65bcbfc8faf3ad75572d36bd2238af5ab374 nonce=27 value=0 signed=true hf=arrowGlacier gasPrice=1000000000)\r\n```\r\nfound it kind of odd that the nonce was having difficulties given that the system that is testing this / where this is happening is fairly solid",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1163498468/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1167409582",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1167409582",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1167409582,
    "node_id": "IC_kwDOB7jojM5FlUGu",
    "user": {
      "login": "samlaf",
      "id": 9342524,
      "node_id": "MDQ6VXNlcjkzNDI1MjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9342524?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/samlaf",
      "html_url": "https://github.com/samlaf",
      "followers_url": "https://api.github.com/users/samlaf/followers",
      "following_url": "https://api.github.com/users/samlaf/following{/other_user}",
      "gists_url": "https://api.github.com/users/samlaf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/samlaf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/samlaf/subscriptions",
      "organizations_url": "https://api.github.com/users/samlaf/orgs",
      "repos_url": "https://api.github.com/users/samlaf/repos",
      "events_url": "https://api.github.com/users/samlaf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/samlaf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-06-27T14:14:49Z",
    "updated_at": "2022-06-28T00:48:37Z",
    "author_association": "CONTRIBUTOR",
    "body": "I would really like to see this issue resolved.\r\nSo far it seems like it's a stochastic error to me... sometimes it happens, sometimes it doesn't (with the same exact code).\r\nNot sure if it depends on network latency, or some other random parameters... been trying things out for 3 hours and can't put my finger on it.\r\n\r\nUPDATE: I managed to solve this problem this morning by increase the timeout parameter on my localhost connection...\r\n```\r\n    localhost: {\r\n      timeout: 100_000\r\n    },\r\n```\r\nSeems like the local node has to do a lot of calls to the backend forked network, and this takes ages... but I feel like hardhat should give users a much more explicit error message; perhaps suggesting this fix?",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1167409582/reactions",
      "total_count": 4,
      "+1": 4,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1177589752",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1177589752",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1177589752,
    "node_id": "IC_kwDOB7jojM5GMJf4",
    "user": {
      "login": "aquib20034",
      "id": 43614239,
      "node_id": "MDQ6VXNlcjQzNjE0MjM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/43614239?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aquib20034",
      "html_url": "https://github.com/aquib20034",
      "followers_url": "https://api.github.com/users/aquib20034/followers",
      "following_url": "https://api.github.com/users/aquib20034/following{/other_user}",
      "gists_url": "https://api.github.com/users/aquib20034/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aquib20034/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aquib20034/subscriptions",
      "organizations_url": "https://api.github.com/users/aquib20034/orgs",
      "repos_url": "https://api.github.com/users/aquib20034/repos",
      "events_url": "https://api.github.com/users/aquib20034/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aquib20034/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-07T13:10:28Z",
    "updated_at": "2022-07-07T13:10:28Z",
    "author_association": "NONE",
    "body": "I also managed this issue using the following configuration.\r\n\r\nmodule.exports = {\r\n   solidity: \"0.8.4\",\r\n   defaultNetwork: \"kovan\",\r\n   networks: {\r\n      hardhat: {},\r\n      kovan: {\r\n         url: API_URL,\r\n         accounts: [`0x${PRIVATE_KEY}`]\r\n      }\r\n   },\r\n   **mocha: {\r\n    timeout: 400000000\r\n  },**\r\n   etherscan: {\r\n    apiKey: ETHERSCAN_API_KEY\r\n  }\r\n} \r\n ",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1177589752/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1207216352",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1207216352",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1207216352,
    "node_id": "IC_kwDOB7jojM5H9Kjg",
    "user": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2022-08-06T13:36:18Z",
    "updated_at": "2022-08-06T13:36:18Z",
    "author_association": "CONTRIBUTOR",
    "body": "This issue was marked as stale because it didn't have any activity in the last 30 days. If you think it's still relevant, please leave a comment indicating so. Otherwise, it will be closed in 7 days.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1207216352/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1207216663",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1207216663",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1207216663,
    "node_id": "IC_kwDOB7jojM5H9KoX",
    "user": {
      "login": "3commascapital",
      "id": 90629478,
      "node_id": "MDQ6VXNlcjkwNjI5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/90629478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/3commascapital",
      "html_url": "https://github.com/3commascapital",
      "followers_url": "https://api.github.com/users/3commascapital/followers",
      "following_url": "https://api.github.com/users/3commascapital/following{/other_user}",
      "gists_url": "https://api.github.com/users/3commascapital/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/3commascapital/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/3commascapital/subscriptions",
      "organizations_url": "https://api.github.com/users/3commascapital/orgs",
      "repos_url": "https://api.github.com/users/3commascapital/repos",
      "events_url": "https://api.github.com/users/3commascapital/events{/privacy}",
      "received_events_url": "https://api.github.com/users/3commascapital/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-06T13:38:30Z",
    "updated_at": "2022-08-06T13:38:30Z",
    "author_association": "NONE",
    "body": "Still relevant",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1207216663/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1216230091",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1216230091",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1216230091,
    "node_id": "IC_kwDOB7jojM5IfjLL",
    "user": {
      "login": "sunwrobert",
      "id": 6511174,
      "node_id": "MDQ6VXNlcjY1MTExNzQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6511174?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sunwrobert",
      "html_url": "https://github.com/sunwrobert",
      "followers_url": "https://api.github.com/users/sunwrobert/followers",
      "following_url": "https://api.github.com/users/sunwrobert/following{/other_user}",
      "gists_url": "https://api.github.com/users/sunwrobert/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sunwrobert/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sunwrobert/subscriptions",
      "organizations_url": "https://api.github.com/users/sunwrobert/orgs",
      "repos_url": "https://api.github.com/users/sunwrobert/repos",
      "events_url": "https://api.github.com/users/sunwrobert/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sunwrobert/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-16T07:03:52Z",
    "updated_at": "2022-08-16T07:03:52Z",
    "author_association": "NONE",
    "body": "+1, still would like to get this solved",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1216230091/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1217261363",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1217261363",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1217261363,
    "node_id": "IC_kwDOB7jojM5Ije8z",
    "user": {
      "login": "feuGeneA",
      "id": 7883777,
      "node_id": "MDQ6VXNlcjc4ODM3Nzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7883777?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/feuGeneA",
      "html_url": "https://github.com/feuGeneA",
      "followers_url": "https://api.github.com/users/feuGeneA/followers",
      "following_url": "https://api.github.com/users/feuGeneA/following{/other_user}",
      "gists_url": "https://api.github.com/users/feuGeneA/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/feuGeneA/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/feuGeneA/subscriptions",
      "organizations_url": "https://api.github.com/users/feuGeneA/orgs",
      "repos_url": "https://api.github.com/users/feuGeneA/repos",
      "events_url": "https://api.github.com/users/feuGeneA/events{/privacy}",
      "received_events_url": "https://api.github.com/users/feuGeneA/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-16T23:12:08Z",
    "updated_at": "2022-08-16T23:12:08Z",
    "author_association": "CONTRIBUTOR",
    "body": "On our internal backlog, I've bumped this up to the highest priority, so that if nothing else it will be discussed by the team. I can't make any promises about whether it'll stay at that priority, much less about when we might add it to our schedule, but once we've discussed it and made such some decision then I'll report back here.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1217261363/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1220832823",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1220832823",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1220832823,
    "node_id": "IC_kwDOB7jojM5IxG43",
    "user": {
      "login": "lut1k",
      "id": 23640322,
      "node_id": "MDQ6VXNlcjIzNjQwMzIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/23640322?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lut1k",
      "html_url": "https://github.com/lut1k",
      "followers_url": "https://api.github.com/users/lut1k/followers",
      "following_url": "https://api.github.com/users/lut1k/following{/other_user}",
      "gists_url": "https://api.github.com/users/lut1k/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lut1k/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lut1k/subscriptions",
      "organizations_url": "https://api.github.com/users/lut1k/orgs",
      "repos_url": "https://api.github.com/users/lut1k/repos",
      "events_url": "https://api.github.com/users/lut1k/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lut1k/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-19T15:55:16Z",
    "updated_at": "2022-08-19T15:55:16Z",
    "author_association": "NONE",
    "body": "+1, still would like to get this solved",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1220832823/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1237327629",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1237327629",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1237327629,
    "node_id": "IC_kwDOB7jojM5JwB8N",
    "user": {
      "login": "alcuadrado",
      "id": 176499,
      "node_id": "MDQ6VXNlcjE3NjQ5OQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/176499?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/alcuadrado",
      "html_url": "https://github.com/alcuadrado",
      "followers_url": "https://api.github.com/users/alcuadrado/followers",
      "following_url": "https://api.github.com/users/alcuadrado/following{/other_user}",
      "gists_url": "https://api.github.com/users/alcuadrado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/alcuadrado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/alcuadrado/subscriptions",
      "organizations_url": "https://api.github.com/users/alcuadrado/orgs",
      "repos_url": "https://api.github.com/users/alcuadrado/repos",
      "events_url": "https://api.github.com/users/alcuadrado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/alcuadrado/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T17:22:10Z",
    "updated_at": "2022-09-05T17:22:10Z",
    "author_association": "MEMBER",
    "body": "If anyone wants to tackle this, take a look at https://github.com/NomicFoundation/hardhat/issues/3136",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1237327629/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1249693478",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/2672#issuecomment-1249693478",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/2672",
    "id": 1249693478,
    "node_id": "IC_kwDOB7jojM5KfM8m",
    "user": {
      "login": "ivanvolov",
      "id": 20977697,
      "node_id": "MDQ6VXNlcjIwOTc3Njk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/20977697?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanvolov",
      "html_url": "https://github.com/ivanvolov",
      "followers_url": "https://api.github.com/users/ivanvolov/followers",
      "following_url": "https://api.github.com/users/ivanvolov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanvolov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanvolov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanvolov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanvolov/orgs",
      "repos_url": "https://api.github.com/users/ivanvolov/repos",
      "events_url": "https://api.github.com/users/ivanvolov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanvolov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-16T18:45:09Z",
    "updated_at": "2022-09-16T18:45:09Z",
    "author_association": "NONE",
    "body": "+1 same here",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1249693478/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
