{
  "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
  "repository_url": "https://api.github.com/repos/NomicFoundation/hardhat",
  "labels_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272/labels{/name}",
  "comments_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272/comments",
  "events_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272/events",
  "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272",
  "id": 1408296413,
  "node_id": "I_kwDOB7jojM5T8OXd",
  "number": 3272,
  "title": "RPC response crash for debug_traceTransaction due to stringify",
  "user": {
    "login": "Archethect",
    "id": 1192011,
    "node_id": "MDQ6VXNlcjExOTIwMTE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1192011?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Archethect",
    "html_url": "https://github.com/Archethect",
    "followers_url": "https://api.github.com/users/Archethect/followers",
    "following_url": "https://api.github.com/users/Archethect/following{/other_user}",
    "gists_url": "https://api.github.com/users/Archethect/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Archethect/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Archethect/subscriptions",
    "organizations_url": "https://api.github.com/users/Archethect/orgs",
    "repos_url": "https://api.github.com/users/Archethect/repos",
    "events_url": "https://api.github.com/users/Archethect/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Archethect/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 901960538,
      "node_id": "MDU6TGFiZWw5MDE5NjA1Mzg=",
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/labels/type:bug",
      "name": "type:bug",
      "color": "FBCA04",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 4937698777,
      "node_id": "LA_kwDOB7jojM8AAAABJk9N2Q",
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/labels/effort:moderate",
      "name": "effort:moderate",
      "color": "006B75",
      "default": false,
      "description": ""
    },
    {
      "id": 4937720577,
      "node_id": "LA_kwDOB7jojM8AAAABJk-jAQ",
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/labels/status:ready",
      "name": "status:ready",
      "color": "0E8A16",
      "default": false,
      "description": "This issue is ready to be worked on"
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 6,
  "created_at": "2022-10-13T19:09:27Z",
  "updated_at": "2023-04-17T13:18:31Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Context:\r\n\r\nI am setting up a local hardhat node in combination with blockscout to do some local tests.\r\nWhen blockscout starts fetching data through the RPC endpoint, the hardhat node fails with the following error:\r\n\r\n```\r\n/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:155\r\n    res.end(JSON.stringify(rpcResp));\r\n                 ^\r\nRangeError: Invalid string length\r\n    at JSON.stringify (<anonymous>)\r\n    at JsonRpcHandler._sendResponse (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:155:18)\r\n    at Server.JsonRpcHandler.handleHttp (/usr/src/app/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:48:12)\r\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\r\nerror Command failed with exit code 1.\r\n```\r\n\r\nIn my case the calls that brake it are:\r\n```\r\n{\"jsonrpc\":\"2.0\", \"method\":\"debug_traceTransaction\", \"params\":[\"0xe751022dd3074ae061939331ceca6b05e2f679c9f92aff6a9e9ae9a033b6fc84\", {\"tracer\": \"callTracer\"}], \"id\":1}\r\n```\r\n\r\n\r\nHardhat version: v2.10.1\r\nNode version: v14\r\n\r\nI suppose the issue is related to https://github.com/NomicFoundation/hardhat/pull/2512 and https://github.com/NomicFoundation/hardhat/issues/1668\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272/reactions",
    "total_count": 4,
    "+1": 4,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1278062039",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1278062039",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1278062039,
    "node_id": "IC_kwDOB7jojM5MLa3X",
    "user": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2022-10-13T19:09:49Z",
    "updated_at": "2022-10-13T19:09:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "This issue is also being [tracked on Linear](https://linear.app/nomic-foundation/issue/HH-1259/rpc-response-crash-due-to-stringify-[nomicfoundationhardhat3272]).\n\nWe use Linear to manage our development process, but we keep the conversations on Github.\n\nLINEAR-ID: 79edef4a-3802-41a3-9ed8-fad0924b23c5",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1278062039/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1291234013",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1291234013",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1291234013,
    "node_id": "IC_kwDOB7jojM5M9qrd",
    "user": {
      "login": "hadfieldn",
      "id": 22274,
      "node_id": "MDQ6VXNlcjIyMjc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/22274?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hadfieldn",
      "html_url": "https://github.com/hadfieldn",
      "followers_url": "https://api.github.com/users/hadfieldn/followers",
      "following_url": "https://api.github.com/users/hadfieldn/following{/other_user}",
      "gists_url": "https://api.github.com/users/hadfieldn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hadfieldn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hadfieldn/subscriptions",
      "organizations_url": "https://api.github.com/users/hadfieldn/orgs",
      "repos_url": "https://api.github.com/users/hadfieldn/repos",
      "events_url": "https://api.github.com/users/hadfieldn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hadfieldn/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-10-25T23:10:56Z",
    "updated_at": "2022-10-25T23:10:56Z",
    "author_association": "NONE",
    "body": "Running into this issue as well.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1291234013/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1298426163",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1298426163",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1298426163,
    "node_id": "IC_kwDOB7jojM5NZGkz",
    "user": {
      "login": "fvictorio",
      "id": 417134,
      "node_id": "MDQ6VXNlcjQxNzEzNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/417134?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fvictorio",
      "html_url": "https://github.com/fvictorio",
      "followers_url": "https://api.github.com/users/fvictorio/followers",
      "following_url": "https://api.github.com/users/fvictorio/following{/other_user}",
      "gists_url": "https://api.github.com/users/fvictorio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fvictorio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fvictorio/subscriptions",
      "organizations_url": "https://api.github.com/users/fvictorio/orgs",
      "repos_url": "https://api.github.com/users/fvictorio/repos",
      "events_url": "https://api.github.com/users/fvictorio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fvictorio/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-01T12:14:42Z",
    "updated_at": "2022-11-01T12:14:42Z",
    "author_association": "MEMBER",
    "body": "Thanks for reporting this @Archethect, I can confirm this is a bug.",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1298426163/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1318406811",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1318406811",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1318406811,
    "node_id": "IC_kwDOB7jojM5OlUqb",
    "user": {
      "login": "srinjoychakravarty",
      "id": 1481037,
      "node_id": "MDQ6VXNlcjE0ODEwMzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1481037?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/srinjoychakravarty",
      "html_url": "https://github.com/srinjoychakravarty",
      "followers_url": "https://api.github.com/users/srinjoychakravarty/followers",
      "following_url": "https://api.github.com/users/srinjoychakravarty/following{/other_user}",
      "gists_url": "https://api.github.com/users/srinjoychakravarty/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/srinjoychakravarty/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/srinjoychakravarty/subscriptions",
      "organizations_url": "https://api.github.com/users/srinjoychakravarty/orgs",
      "repos_url": "https://api.github.com/users/srinjoychakravarty/repos",
      "events_url": "https://api.github.com/users/srinjoychakravarty/events{/privacy}",
      "received_events_url": "https://api.github.com/users/srinjoychakravarty/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-17T10:18:28Z",
    "updated_at": "2022-11-18T04:04:19Z",
    "author_association": "NONE",
    "body": "Running into this exact same issue as of yesterday:\r\n\r\n<img width=\"964\" alt=\"Screenshot 2022-11-17 at 5 09 36 AM\" src=\"https://user-images.githubusercontent.com/1481037/202420121-646952c1-b594-4b28-a64c-e37384171f53.png\">\r\n\r\n\r\n>     \"hardhat\": \"^2.12.2\",\r\npackage.json\r\n\r\n@Archethect @fvictorio @hadfieldn is there anyway to resolve this? 🤔",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1318406811/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1340477703",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1340477703",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1340477703,
    "node_id": "IC_kwDOB7jojM5P5hEH",
    "user": {
      "login": "SuperHero123123",
      "id": 102787464,
      "node_id": "U_kgDOBiBpiA",
      "avatar_url": "https://avatars.githubusercontent.com/u/102787464?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/SuperHero123123",
      "html_url": "https://github.com/SuperHero123123",
      "followers_url": "https://api.github.com/users/SuperHero123123/followers",
      "following_url": "https://api.github.com/users/SuperHero123123/following{/other_user}",
      "gists_url": "https://api.github.com/users/SuperHero123123/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/SuperHero123123/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SuperHero123123/subscriptions",
      "organizations_url": "https://api.github.com/users/SuperHero123123/orgs",
      "repos_url": "https://api.github.com/users/SuperHero123123/repos",
      "events_url": "https://api.github.com/users/SuperHero123123/events{/privacy}",
      "received_events_url": "https://api.github.com/users/SuperHero123123/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-12-07T06:53:20Z",
    "updated_at": "2022-12-07T06:53:20Z",
    "author_association": "NONE",
    "body": "> Thanks for reporting this @Archethect, I can confirm this is a bug.\r\n\r\nmeet the same bug today, is there anyway to resolve this?",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1340477703/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1511332651",
    "html_url": "https://github.com/NomicFoundation/hardhat/issues/3272#issuecomment-1511332651",
    "issue_url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/3272",
    "id": 1511332651,
    "node_id": "IC_kwDOB7jojM5aFRsr",
    "user": {
      "login": "antazoey",
      "id": 19540978,
      "node_id": "MDQ6VXNlcjE5NTQwOTc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/19540978?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/antazoey",
      "html_url": "https://github.com/antazoey",
      "followers_url": "https://api.github.com/users/antazoey/followers",
      "following_url": "https://api.github.com/users/antazoey/following{/other_user}",
      "gists_url": "https://api.github.com/users/antazoey/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/antazoey/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/antazoey/subscriptions",
      "organizations_url": "https://api.github.com/users/antazoey/orgs",
      "repos_url": "https://api.github.com/users/antazoey/repos",
      "events_url": "https://api.github.com/users/antazoey/events{/privacy}",
      "received_events_url": "https://api.github.com/users/antazoey/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-04-17T13:18:30Z",
    "updated_at": "2023-04-17T13:18:30Z",
    "author_association": "NONE",
    "body": "I am getting this error, and in my response, it is mostly empty zeroes... A lot of empty byte strings. I tried on Anvil, Geth --dev, eth Tester... They have the expected data response size. So maybe something is messing up there?",
    "reactions": {
      "url": "https://api.github.com/repos/NomicFoundation/hardhat/issues/comments/1511332651/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
