{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/16338",
  "id": 306370000,
  "node_id": "MDU6SXNzdWUzMDYzNzAwMDA=",
  "number": 16338,
  "title": "Why does the private network connect to the public network when starting?",
  "user": {
    "login": "IcyLemon",
    "id": 19788374,
    "node_id": "MDQ6VXNlcjE5Nzg4Mzc0",
    "avatar_url": "https://avatars.githubusercontent.com/u/19788374?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/IcyLemon",
    "html_url": "https://github.com/IcyLemon",
    "followers_url": "https://api.github.com/users/IcyLemon/followers",
    "following_url": "https://api.github.com/users/IcyLemon/following{/other_user}",
    "gists_url": "https://api.github.com/users/IcyLemon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/IcyLemon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/IcyLemon/subscriptions",
    "organizations_url": "https://api.github.com/users/IcyLemon/orgs",
    "repos_url": "https://api.github.com/users/IcyLemon/repos",
    "events_url": "https://api.github.com/users/IcyLemon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/IcyLemon/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 856638432,
      "node_id": "MDU6TGFiZWw4NTY2Mzg0MzI=",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/status:inactive",
      "name": "status:inactive",
      "color": "ffffff",
      "default": false,
      "description": null
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 6,
  "created_at": "2018-03-19T08:27:25Z",
  "updated_at": "2019-05-02T02:33:47Z",
  "closed_at": "2019-05-02T02:33:47Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I found a strange problem and confused me.\r\n\r\nI want to create a private network, the gensis file(my-gensis.json) is as follows:\r\n```\r\n{\r\n  \"config\": {\r\n        \"chainId\": 15,\r\n        \"homesteadBlock\": 0,\r\n        \"eip155Block\": 0,\r\n        \"eip158Block\": 0\r\n    },\r\n    \"coinbase\" : \"0x0000000000000000000000000000000000000000\",\r\n    ......\r\n}\r\n```\r\nhere, the chainId is 15.\r\n\r\nFirst, I initialized successfully as follows:\r\n`./geth init my-gensis.json --datadir data`\r\n\r\nThen I tried to start the geth as follows:\r\n`./geth --rpc --rpcport 8545 --datadir data --port 30001 --rpcapi personal,db,eth,miner,net,web3 --networkid 100000 --nodiscover console`\r\n\r\nThe startup log is as follows:\r\n```\r\nWARN [03-19|15:56:35] No etherbase set and no accounts found as default \r\nINFO [03-19|15:56:35] Starting peer-to-peer node               instance=Geth/centos-dev-125-1/v1.7.3-stable/linux-amd64/go1.8.3\r\nINFO [03-19|15:56:35] Allocated cache and file handles         database=/home/work/.ethereum/geth/chaindata cache=128 handles=1024\r\n**INFO [03-19|15:56:35] Initialised chain configuration          config=\"{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}\"**\r\n```\r\nNote the bold context: ChainId is 1, not 15 defined in my gensis file! Other parameters were also inconsistent with the definition in the my-gensis.json file. It seemed that the private network connected to the public network?\r\n\r\nI checked over and over and was sure that the data dir, gensis file, command line were all ok. \r\n\r\nWho encountered this and resolved?\r\n\r\nThanks a lot.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
  "closed_by": {
    "login": "stale[bot]",
    "id": 26384082,
    "node_id": "MDM6Qm90MjYzODQwODI=",
    "avatar_url": "https://avatars.githubusercontent.com/in/1724?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stale%5Bbot%5D",
    "html_url": "https://github.com/apps/stale",
    "followers_url": "https://api.github.com/users/stale%5Bbot%5D/followers",
    "following_url": "https://api.github.com/users/stale%5Bbot%5D/following{/other_user}",
    "gists_url": "https://api.github.com/users/stale%5Bbot%5D/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stale%5Bbot%5D/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stale%5Bbot%5D/subscriptions",
    "organizations_url": "https://api.github.com/users/stale%5Bbot%5D/orgs",
    "repos_url": "https://api.github.com/users/stale%5Bbot%5D/repos",
    "events_url": "https://api.github.com/users/stale%5Bbot%5D/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stale%5Bbot%5D/received_events",
    "type": "Bot",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374136370",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-374136370",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 374136370,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NDEzNjM3MA==",
    "user": {
      "login": "holiman",
      "id": 142290,
      "node_id": "MDQ6VXNlcjE0MjI5MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/holiman",
      "html_url": "https://github.com/holiman",
      "followers_url": "https://api.github.com/users/holiman/followers",
      "following_url": "https://api.github.com/users/holiman/following{/other_user}",
      "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
      "organizations_url": "https://api.github.com/users/holiman/orgs",
      "repos_url": "https://api.github.com/users/holiman/repos",
      "events_url": "https://api.github.com/users/holiman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/holiman/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-19T08:36:09Z",
    "updated_at": "2018-03-19T08:36:09Z",
    "author_association": "MEMBER",
    "body": "That looks very odd. Additionally, `database=/home/work/.ethereum/geth/chaindata` shows that it totally ignored your `--datadir`. \r\nRunning your comand locally, it works for me:\r\n```\r\n[user@work bin]$ ./geth --rpc --rpcport 8545 --datadir data --port 30001 --rpcapi personal,db,eth,miner,net,web3 --networkid 100000 --nodiscover console\r\nINFO [03-19|09:32:56] Maximum peer count                       ETH=25 LES=0 total=25\r\nINFO [03-19|09:32:56] Starting peer-to-peer node               instance=Geth/v1.8.3-unstable-6494f4e8/linux-amd64/go1.10\r\nINFO [03-19|09:32:56] Allocated cache and file handles         database=/home/user/go/src/github.com/ethereum/go-ethereum/build/bin/data/geth/chaindata cache=768 handles=512\r\n```\r\nCould you try with a more recent release and see if you get the same problem? ",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374136370/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374163672",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-374163672",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 374163672,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NDE2MzY3Mg==",
    "user": {
      "login": "IcyLemon",
      "id": 19788374,
      "node_id": "MDQ6VXNlcjE5Nzg4Mzc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19788374?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/IcyLemon",
      "html_url": "https://github.com/IcyLemon",
      "followers_url": "https://api.github.com/users/IcyLemon/followers",
      "following_url": "https://api.github.com/users/IcyLemon/following{/other_user}",
      "gists_url": "https://api.github.com/users/IcyLemon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/IcyLemon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/IcyLemon/subscriptions",
      "organizations_url": "https://api.github.com/users/IcyLemon/orgs",
      "repos_url": "https://api.github.com/users/IcyLemon/repos",
      "events_url": "https://api.github.com/users/IcyLemon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/IcyLemon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-19T10:18:29Z",
    "updated_at": "2018-03-19T10:18:29Z",
    "author_association": "NONE",
    "body": "@holiman \r\nI use geth geth-linux-amd64-1.7.3 in Centos 7.2 64.\r\n\r\nI found the reason and thought that this is possibly a bug of geth: **this problem is related to the path**\r\n\r\nMy directory structure of the geth is as follows:\r\n```\r\ngeth-linux-amd64-1.7.3/\r\n    -- geth\r\n    -- my-gensis.json\r\n    -- node-1/\r\n        -- data\r\n```\r\n Firstly, initialized successfully as follows:\r\n`./geth init my-gensis.json --datadir ./node-1/data`\r\n\r\nWhen I started the geth in the geth-linux-amd64-1.7.3 folder as follows:\r\n```\r\ncd geth-linux-amd64-1.7.3\r\n./geth --rpc  --datadir ./node-1/data  --rpcapi eth,miner,net,web3  --networkid 15125 console\r\n```\r\nThe problem I described before occurred: It connected to chainId 1.\r\n\r\nBut when I entered into node-1 folder and start the geth as follows:\r\n```\r\ncd geth-linux-amd64-1.7.3/node-1\r\n../geth --rpc  --datadir ./data  --rpcapi db,eth,miner,net,web3  --networkid 15125 console\r\n```\r\nIt worked fine!\r\n\r\nOn the other hand, I found that there must be a subdirectory such as data under the node-1. If the structure is as follows:\r\n```\r\ngeth-linux-amd64-1.7.3/\r\n    -- geth\r\n    -- my-gensis.json\r\n    -- node-1/\r\n```\r\nit doesn't work(always connect to chainId 1) no matter where you start the geth.\r\n\r\nI don't know if this is a bug, but it is very weird for me.\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374163672/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374216716",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-374216716",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 374216716,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NDIxNjcxNg==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-19T13:46:13Z",
    "updated_at": "2018-03-19T13:46:13Z",
    "author_association": "MEMBER",
    "body": "Put the `--datadir` before `init`.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374216716/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374437776",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-374437776",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 374437776,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NDQzNzc3Ng==",
    "user": {
      "login": "IcyLemon",
      "id": 19788374,
      "node_id": "MDQ6VXNlcjE5Nzg4Mzc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19788374?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/IcyLemon",
      "html_url": "https://github.com/IcyLemon",
      "followers_url": "https://api.github.com/users/IcyLemon/followers",
      "following_url": "https://api.github.com/users/IcyLemon/following{/other_user}",
      "gists_url": "https://api.github.com/users/IcyLemon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/IcyLemon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/IcyLemon/subscriptions",
      "organizations_url": "https://api.github.com/users/IcyLemon/orgs",
      "repos_url": "https://api.github.com/users/IcyLemon/repos",
      "events_url": "https://api.github.com/users/IcyLemon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/IcyLemon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-20T01:08:07Z",
    "updated_at": "2018-03-20T01:08:07Z",
    "author_association": "NONE",
    "body": "@karalabe \r\nPut before and after were both tried,  and the result is the same.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374437776/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 1,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374444360",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-374444360",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 374444360,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3NDQ0NDM2MA==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-20T01:46:58Z",
    "updated_at": "2018-03-20T01:46:58Z",
    "author_association": "MEMBER",
    "body": "Oh, I misunderstood the issue, my apologies.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/374444360/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/475092422",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16338#issuecomment-475092422",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16338",
    "id": 475092422,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NTA5MjQyMg==",
    "user": {
      "login": "stale[bot]",
      "id": 26384082,
      "node_id": "MDM6Qm90MjYzODQwODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/1724?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stale%5Bbot%5D",
      "html_url": "https://github.com/apps/stale",
      "followers_url": "https://api.github.com/users/stale%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/stale%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/stale%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stale%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stale%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/stale%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/stale%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/stale%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stale%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "created_at": "2019-03-21T02:10:44Z",
    "updated_at": "2019-03-21T02:10:44Z",
    "author_association": "NONE",
    "body": "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/475092422/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
