{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/16599",
  "id": 318666054,
  "node_id": "MDU6SXNzdWUzMTg2NjYwNTQ=",
  "number": 16599,
  "title": "Tracer accessed out of bound stack",
  "user": {
    "login": "linuxion",
    "id": 25755605,
    "node_id": "MDQ6VXNlcjI1NzU1NjA1",
    "avatar_url": "https://avatars.githubusercontent.com/u/25755605?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/linuxion",
    "html_url": "https://github.com/linuxion",
    "followers_url": "https://api.github.com/users/linuxion/followers",
    "following_url": "https://api.github.com/users/linuxion/following{/other_user}",
    "gists_url": "https://api.github.com/users/linuxion/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/linuxion/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/linuxion/subscriptions",
    "organizations_url": "https://api.github.com/users/linuxion/orgs",
    "repos_url": "https://api.github.com/users/linuxion/repos",
    "events_url": "https://api.github.com/users/linuxion/events{/privacy}",
    "received_events_url": "https://api.github.com/users/linuxion/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2018-04-28T20:23:42Z",
  "updated_at": "2018-07-26T09:42:00Z",
  "closed_at": "2018-07-26T09:42:00Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: 1.8.4-unstable\r\nOS & Version: Ubuntu 16.04\r\nCommit hash : 6cdfb9a3\r\n\r\n#### Expected behaviour\r\nRun without `out of bound memory` error.\r\n\r\n#### Actual behaviour\r\nGet a lot of errors of this type.\r\n````\r\nWARN [04-28|20:00:17] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:00:19] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:00:19] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:00:33] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:00:33] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:00:46] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:01:09] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|20:01:09] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\n````\r\n#### Steps to reproduce the behaviour\r\nRun geth in archive mode OR trace `0xc0f77f2f18e90bcfc5e3074e8faab3b925058474c6683d98f5313673c909c99f` transaction, for example.\r\n\r\n#### Backtrace\r\n\r\n````\r\nWARN [04-28|16:08:55] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=1\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=3\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=4\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=5\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=6\r\nWARN [04-28|16:08:59] Tracer accessed out of bound stack       size=0 index=2\r\nWARN [04-28|16:09:07] Tracer accessed out of bound memory      available=96  offset=2147483647 size=0]\r\n````\r\n\r\n#### Thoughts  \r\n[slice](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L95) and [getUint](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L106) functions throwing the error only affect the memory, but [peek](https://github.com/ethereum/go-ethereum/blob/a5c0bbb4f4c321c355637ef57fff807857128c6b/eth/tracers/tracer.go#L149) affects the stack. \r\n\r\n@karalabe, can this error be the cause of incorrect output by the tracer?\r\n\r\nThank you!",
  "closed_by": {
    "login": "karalabe",
    "id": 129561,
    "node_id": "MDQ6VXNlcjEyOTU2MQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/karalabe",
    "html_url": "https://github.com/karalabe",
    "followers_url": "https://api.github.com/users/karalabe/followers",
    "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
    "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
    "organizations_url": "https://api.github.com/users/karalabe/orgs",
    "repos_url": "https://api.github.com/users/karalabe/repos",
    "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/karalabe/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/408040422",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16599#issuecomment-408040422",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16599",
    "id": 408040422,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwODA0MDQyMg==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-26T09:42:00Z",
    "updated_at": "2018-07-26T09:42:00Z",
    "author_association": "MEMBER",
    "body": "I've seen these \"errors\". They're not really errors, rather some contracts explicitly do invalid operations (e.g. try to access memory area that doesn't exist). When the tracer is running, it tries to \"gather\" the infos from potentially invalid parameters, and just tells you it's not possible. The contracts will probably throw in the next step when the EVM refuses the accesses too.\r\n\r\nI may be wrong of course, but I did see many contracts try to break consensus with nasty params, so I'd chalk it up for those unless you explicitly know the contract/transaction is ok. In that case, please provide more details.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/408040422/reactions",
      "total_count": 2,
      "+1": 2,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
