{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/16698",
  "id": 320847622,
  "node_id": "MDU6SXNzdWUzMjA4NDc2MjI=",
  "number": 16698,
  "title": "Why throw errGasUintOverflow when memory size overflows?",
  "user": {
    "login": "viniul",
    "id": 20932074,
    "node_id": "MDQ6VXNlcjIwOTMyMDc0",
    "avatar_url": "https://avatars.githubusercontent.com/u/20932074?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/viniul",
    "html_url": "https://github.com/viniul",
    "followers_url": "https://api.github.com/users/viniul/followers",
    "following_url": "https://api.github.com/users/viniul/following{/other_user}",
    "gists_url": "https://api.github.com/users/viniul/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/viniul/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/viniul/subscriptions",
    "organizations_url": "https://api.github.com/users/viniul/orgs",
    "repos_url": "https://api.github.com/users/viniul/repos",
    "events_url": "https://api.github.com/users/viniul/events{/privacy}",
    "received_events_url": "https://api.github.com/users/viniul/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2018-05-07T15:25:12Z",
  "updated_at": "2018-05-10T07:38:17Z",
  "closed_at": "2018-05-10T07:38:17Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "In line 178 in `core/vm/interpreter.go`, an errGasUintOverflow is returned. However, it seems to that this error is returned when actually the memory size overflows. Is this true? And if so, is this not a bit misleading? \r\n\r\nBest, \r\nVincent\r\nhttps://github.com/ethereum/go-ethereum/blob/45bd4feddeadfbde5d1e560797155aacb0abbadf/core/vm/interpreter.go#L178",
  "closed_by": {
    "login": "karalabe",
    "id": 129561,
    "node_id": "MDQ6VXNlcjEyOTU2MQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/karalabe",
    "html_url": "https://github.com/karalabe",
    "followers_url": "https://api.github.com/users/karalabe/followers",
    "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
    "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
    "organizations_url": "https://api.github.com/users/karalabe/orgs",
    "repos_url": "https://api.github.com/users/karalabe/repos",
    "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/karalabe/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/387977565",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/16698#issuecomment-387977565",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/16698",
    "id": 387977565,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4Nzk3NzU2NQ==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-05-10T07:38:17Z",
    "updated_at": "2018-05-10T07:38:17Z",
    "author_association": "MEMBER",
    "body": "The EVM in theory is considered to have infinite amount of memory. In practice, the memory is always limited by the available gas, which is many many orders of magnitude smaller than what your machine could support. If your memory request overflows the uint64 counter, then it surely overflows the gas allowance too.\r\n\r\nTL;DR You cannot overflow memory by design, only gas.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/387977565/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
