{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/21916",
  "id": 752778990,
  "node_id": "MDU6SXNzdWU3NTI3Nzg5OTA=",
  "number": 21916,
  "title": "Failed to store pivot block number       err=\"leveldb/table: corruption on data-block (pos=384824320): checksum mismatch, want=0x0 got=0xf0423001 [file=592568.ldb]\"",
  "user": {
    "login": "vijay055",
    "id": 13768108,
    "node_id": "MDQ6VXNlcjEzNzY4MTA4",
    "avatar_url": "https://avatars.githubusercontent.com/u/13768108?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vijay055",
    "html_url": "https://github.com/vijay055",
    "followers_url": "https://api.github.com/users/vijay055/followers",
    "following_url": "https://api.github.com/users/vijay055/following{/other_user}",
    "gists_url": "https://api.github.com/users/vijay055/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vijay055/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vijay055/subscriptions",
    "organizations_url": "https://api.github.com/users/vijay055/orgs",
    "repos_url": "https://api.github.com/users/vijay055/repos",
    "events_url": "https://api.github.com/users/vijay055/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vijay055/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 13,
  "created_at": "2020-11-28T22:13:49Z",
  "updated_at": "2021-10-20T06:23:25Z",
  "closed_at": "2021-10-20T06:23:25Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `v1.9.19`\r\nOS & Version: Windows 10 ( 1 tb SSD , Intel core 17 )\r\nCommit hash : (if `develop`)\r\n\r\n#### Expected behaviour\r\nwaiting for all block headers to be downloaded and start mining\r\n\r\n#### Actual behaviour\r\nFailed to store pivot block number       err=\"leveldb/table: corruption on data-block (pos=384824320): checksum mismatch, want=0x0 got=0xf0423001 [file=592568.ldb]\"\r\n\r\n#### Steps to reproduce the behaviour\r\nGeth connected to mainnet , downloaded all most all blocks just behind 100 (took more than 2 weeks)( nearly 400 GB data)\r\n\r\neth.syncing\r\n  currentBlock: 11349254,\r\n  highestBlock: 11349325,\r\n  knownStates: 445589841,\r\n  pulledStates: 445589568,\r\n  startingBlock: 11349042\r\n\r\n\r\n",
  "closed_by": {
    "login": "holiman",
    "id": 142290,
    "node_id": "MDQ6VXNlcjE0MjI5MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/holiman",
    "html_url": "https://github.com/holiman",
    "followers_url": "https://api.github.com/users/holiman/followers",
    "following_url": "https://api.github.com/users/holiman/following{/other_user}",
    "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
    "organizations_url": "https://api.github.com/users/holiman/orgs",
    "repos_url": "https://api.github.com/users/holiman/repos",
    "events_url": "https://api.github.com/users/holiman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/holiman/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735312706",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735312706",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735312706,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTMxMjcwNg==",
    "user": {
      "login": "ligi",
      "id": 111600,
      "node_id": "MDQ6VXNlcjExMTYwMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/111600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ligi",
      "html_url": "https://github.com/ligi",
      "followers_url": "https://api.github.com/users/ligi/followers",
      "following_url": "https://api.github.com/users/ligi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ligi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ligi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ligi/subscriptions",
      "organizations_url": "https://api.github.com/users/ligi/orgs",
      "repos_url": "https://api.github.com/users/ligi/repos",
      "events_url": "https://api.github.com/users/ligi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ligi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-29T01:03:18Z",
    "updated_at": "2020-11-29T01:03:18Z",
    "author_association": "MEMBER",
    "body": "did you at some point have a unclean shutdown of geth? e.g. a reboot / crash / ..",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735312706/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735354783",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735354783",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735354783,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTM1NDc4Mw==",
    "user": {
      "login": "vijay055",
      "id": 13768108,
      "node_id": "MDQ6VXNlcjEzNzY4MTA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/13768108?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vijay055",
      "html_url": "https://github.com/vijay055",
      "followers_url": "https://api.github.com/users/vijay055/followers",
      "following_url": "https://api.github.com/users/vijay055/following{/other_user}",
      "gists_url": "https://api.github.com/users/vijay055/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vijay055/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vijay055/subscriptions",
      "organizations_url": "https://api.github.com/users/vijay055/orgs",
      "repos_url": "https://api.github.com/users/vijay055/repos",
      "events_url": "https://api.github.com/users/vijay055/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vijay055/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-29T07:21:46Z",
    "updated_at": "2020-11-29T07:26:26Z",
    "author_association": "NONE",
    "body": "@ligi \r\nYes , i did stop at one point when i moved files to external SSD ( moved around 250gb from internal SSD to external SSD) then started geth ( geth was put in .bat file, so stopped batch file and started again after moving files )\r\nit was downloading more than 100 Gb of headers after that.\r\n\r\nnow ..I have installed latest geth v1.9.24 \r\ni have removed particular .db file and started again..\r\nIts importing new block headers..but i get lots of  \"initializing fast sync bloom...\"\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735354783/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735355219",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735355219",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735355219,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTM1NTIxOQ==",
    "user": {
      "login": "ligi",
      "id": 111600,
      "node_id": "MDQ6VXNlcjExMTYwMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/111600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ligi",
      "html_url": "https://github.com/ligi",
      "followers_url": "https://api.github.com/users/ligi/followers",
      "following_url": "https://api.github.com/users/ligi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ligi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ligi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ligi/subscriptions",
      "organizations_url": "https://api.github.com/users/ligi/orgs",
      "repos_url": "https://api.github.com/users/ligi/repos",
      "events_url": "https://api.github.com/users/ligi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ligi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-29T07:27:22Z",
    "updated_at": "2020-11-29T07:27:22Z",
    "author_association": "MEMBER",
    "body": "How did you stop geth?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735355219/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735355278",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735355278",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735355278,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTM1NTI3OA==",
    "user": {
      "login": "vijay055",
      "id": 13768108,
      "node_id": "MDQ6VXNlcjEzNzY4MTA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/13768108?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vijay055",
      "html_url": "https://github.com/vijay055",
      "followers_url": "https://api.github.com/users/vijay055/followers",
      "following_url": "https://api.github.com/users/vijay055/following{/other_user}",
      "gists_url": "https://api.github.com/users/vijay055/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vijay055/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vijay055/subscriptions",
      "organizations_url": "https://api.github.com/users/vijay055/orgs",
      "repos_url": "https://api.github.com/users/vijay055/repos",
      "events_url": "https://api.github.com/users/vijay055/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vijay055/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-29T07:28:00Z",
    "updated_at": "2020-11-29T07:28:00Z",
    "author_association": "NONE",
    "body": "stopped the batch file..Ctrl+c",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735355278/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735381053",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735381053",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735381053,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTM4MTA1Mw==",
    "user": {
      "login": "funkekaiser",
      "id": 31299739,
      "node_id": "MDQ6VXNlcjMxMjk5NzM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/31299739?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/funkekaiser",
      "html_url": "https://github.com/funkekaiser",
      "followers_url": "https://api.github.com/users/funkekaiser/followers",
      "following_url": "https://api.github.com/users/funkekaiser/following{/other_user}",
      "gists_url": "https://api.github.com/users/funkekaiser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/funkekaiser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/funkekaiser/subscriptions",
      "organizations_url": "https://api.github.com/users/funkekaiser/orgs",
      "repos_url": "https://api.github.com/users/funkekaiser/repos",
      "events_url": "https://api.github.com/users/funkekaiser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/funkekaiser/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-29T11:48:28Z",
    "updated_at": "2020-11-29T11:48:28Z",
    "author_association": "NONE",
    "body": "I have the same problem, it corrupted 3 times on 2 different SSDs.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735381053/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735703965",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735703965",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735703965,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTcwMzk2NQ==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-30T10:38:23Z",
    "updated_at": "2020-11-30T10:38:23Z",
    "author_association": "MEMBER",
    "body": "@vijay055 You can't just remove a file from the database, if you delete part of the dataset you'll get bad blocks. You'll need to resync.\r\n\r\n\r\n@derbrachialist What os? What error message? Any logs?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735703965/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735706268",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735706268",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735706268,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTcwNjI2OA==",
    "user": {
      "login": "funkekaiser",
      "id": 31299739,
      "node_id": "MDQ6VXNlcjMxMjk5NzM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/31299739?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/funkekaiser",
      "html_url": "https://github.com/funkekaiser",
      "followers_url": "https://api.github.com/users/funkekaiser/followers",
      "following_url": "https://api.github.com/users/funkekaiser/following{/other_user}",
      "gists_url": "https://api.github.com/users/funkekaiser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/funkekaiser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/funkekaiser/subscriptions",
      "organizations_url": "https://api.github.com/users/funkekaiser/orgs",
      "repos_url": "https://api.github.com/users/funkekaiser/repos",
      "events_url": "https://api.github.com/users/funkekaiser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/funkekaiser/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-30T10:42:57Z",
    "updated_at": "2020-11-30T10:43:22Z",
    "author_association": "NONE",
    "body": "Manjaro Gnome\r\nsame error message, did not save any logs. Got frustrated after only comments on github that I found were that the ssd must be broken. I'm running on a brand new nvme ssd, bought for the purpose of running a node and even tried my old 2.5 ssd. switched to [openethereum](https://github.com/openethereum/openethereum) for now.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735706268/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735880316",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735880316",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735880316,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTg4MDMxNg==",
    "user": {
      "login": "vijay055",
      "id": 13768108,
      "node_id": "MDQ6VXNlcjEzNzY4MTA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/13768108?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vijay055",
      "html_url": "https://github.com/vijay055",
      "followers_url": "https://api.github.com/users/vijay055/followers",
      "following_url": "https://api.github.com/users/vijay055/following{/other_user}",
      "gists_url": "https://api.github.com/users/vijay055/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vijay055/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vijay055/subscriptions",
      "organizations_url": "https://api.github.com/users/vijay055/orgs",
      "repos_url": "https://api.github.com/users/vijay055/repos",
      "events_url": "https://api.github.com/users/vijay055/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vijay055/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-30T16:06:40Z",
    "updated_at": "2020-11-30T16:06:40Z",
    "author_association": "NONE",
    "body": "@karalabe \r\ni removed and started the geth , it went on for while ( remember it did some compression on the db files i guess)\r\nbut I have given up at that point.\r\n\r\n@derbrachialist I also bought a new 1 TB SSD and it failed. Now the issue is SSD with or geth. ?\r\nor is that bcoz I used external SSD and if there is slight shaking in the USB connections it is corrupting files ??? just guessing..",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735880316/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735883635",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-735883635",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 735883635,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczNTg4MzYzNQ==",
    "user": {
      "login": "funkekaiser",
      "id": 31299739,
      "node_id": "MDQ6VXNlcjMxMjk5NzM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/31299739?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/funkekaiser",
      "html_url": "https://github.com/funkekaiser",
      "followers_url": "https://api.github.com/users/funkekaiser/followers",
      "following_url": "https://api.github.com/users/funkekaiser/following{/other_user}",
      "gists_url": "https://api.github.com/users/funkekaiser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/funkekaiser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/funkekaiser/subscriptions",
      "organizations_url": "https://api.github.com/users/funkekaiser/orgs",
      "repos_url": "https://api.github.com/users/funkekaiser/repos",
      "events_url": "https://api.github.com/users/funkekaiser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/funkekaiser/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-11-30T16:12:23Z",
    "updated_at": "2020-11-30T16:13:36Z",
    "author_association": "NONE",
    "body": "It corrupted both on my external usb and internal m.2 ssd.\r\n\r\nIt is definitely a software issue, because of all the people having problems at once.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/735883635/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/783128508",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-783128508",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 783128508,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc4MzEyODUwOA==",
    "user": {
      "login": "ppershing",
      "id": 837681,
      "node_id": "MDQ6VXNlcjgzNzY4MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/837681?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ppershing",
      "html_url": "https://github.com/ppershing",
      "followers_url": "https://api.github.com/users/ppershing/followers",
      "following_url": "https://api.github.com/users/ppershing/following{/other_user}",
      "gists_url": "https://api.github.com/users/ppershing/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ppershing/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ppershing/subscriptions",
      "organizations_url": "https://api.github.com/users/ppershing/orgs",
      "repos_url": "https://api.github.com/users/ppershing/repos",
      "events_url": "https://api.github.com/users/ppershing/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ppershing/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-02-22T06:38:54Z",
    "updated_at": "2021-02-22T06:38:54Z",
    "author_association": "NONE",
    "body": "Another instance here. I believe I first saw checksum error. Now, after deleting all data and resyncing I see\r\n\r\n```\r\nCRIT [02-22|00:54:58.104] Failed to write block into disk          err=\"leveldb/table: Writer: keys are not in increasing order: \\\"\\\\xf5R;\\\\x8e\\\\xec\\\\xe0K\\\\x92ꙉ\\\\xab\\\\x8c\\\\xfaH\\\\x99\\\\f\\\\x03\\\\x9d\\\\\\\\\\\\xbaj\\\\xcf,\\\\xb5\\\\xf08\\\\x03m\\\\xfda\\\\xaa\\\\xda\\\\xc09\\\\xae~\\\\x86\\\\xb2\\\\x12\\\\x85\\\\x1cqY{\\\\xc1cJk\\\\xad\\\\x8a\\\\xd2\\\\xf5\\\\x04@}\\\\xc1\\\\x82\\\\xc5\\\\xd9*\\\\xb0\\\\xe9\\\\xf2\\\\xe4V\\\\xc9i=\\\\x1eg\\\\xbf~\\\", \\\"]\\\\xb7P\\\\x99\\\\xfd\\\\xa1p\\\\xc0\\\\xf50\\\\xc4\\\\xf12>\\\\x8dK\\\\xe4\\\\x84\\\\xc9ѐh\\\\x16\\\\xb1\\\\xa6\\\\x8e\\\\xc7\\\\xf8P\\\\xbe\\\\x11p\\\\xf8i\\\\xb6\\\\x9a3\\\\x98.\\\\x85\\\\x95G\\\\x97\\\\x19\\\\xf2\\\\xd2\\\\xeb\\\\x01\\\\x8eE\\\\xa7\\\\xae\\\\xc9\\\\xeb\\\\x83a\\\\x13\\\\xf8~Z\\\\x94\\\\\\\"\\\\x1e\\\\ue415\\\\x92\\\\x1a\\\\x9a\\\\xd1q\\\\x883\\\"\"\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/783128508/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/883002614",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-883002614",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 883002614,
    "node_id": "IC_kwDOAOvK9840oYz2",
    "user": {
      "login": "jayboy-mabushi",
      "id": 60149478,
      "node_id": "MDQ6VXNlcjYwMTQ5NDc4",
      "avatar_url": "https://avatars.githubusercontent.com/u/60149478?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jayboy-mabushi",
      "html_url": "https://github.com/jayboy-mabushi",
      "followers_url": "https://api.github.com/users/jayboy-mabushi/followers",
      "following_url": "https://api.github.com/users/jayboy-mabushi/following{/other_user}",
      "gists_url": "https://api.github.com/users/jayboy-mabushi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jayboy-mabushi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jayboy-mabushi/subscriptions",
      "organizations_url": "https://api.github.com/users/jayboy-mabushi/orgs",
      "repos_url": "https://api.github.com/users/jayboy-mabushi/repos",
      "events_url": "https://api.github.com/users/jayboy-mabushi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jayboy-mabushi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-07-20T02:26:05Z",
    "updated_at": "2021-07-20T02:26:05Z",
    "author_association": "NONE",
    "body": "@derbrachialist  did you find a solution?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/883002614/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/883302327",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-883302327",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 883302327,
    "node_id": "IC_kwDOAOvK9840ph-3",
    "user": {
      "login": "funkekaiser",
      "id": 31299739,
      "node_id": "MDQ6VXNlcjMxMjk5NzM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/31299739?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/funkekaiser",
      "html_url": "https://github.com/funkekaiser",
      "followers_url": "https://api.github.com/users/funkekaiser/followers",
      "following_url": "https://api.github.com/users/funkekaiser/following{/other_user}",
      "gists_url": "https://api.github.com/users/funkekaiser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/funkekaiser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/funkekaiser/subscriptions",
      "organizations_url": "https://api.github.com/users/funkekaiser/orgs",
      "repos_url": "https://api.github.com/users/funkekaiser/repos",
      "events_url": "https://api.github.com/users/funkekaiser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/funkekaiser/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-07-20T11:02:49Z",
    "updated_at": "2021-07-20T11:02:49Z",
    "author_association": "NONE",
    "body": "It corrupted with go-ethereum and openethereum so i guess my new ssd must have been broken. I did not find a solution, I would recommend trying another ssd.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/883302327/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/947365378",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/21916#issuecomment-947365378",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/21916",
    "id": 947365378,
    "node_id": "IC_kwDOAOvK9844d6YC",
    "user": {
      "login": "holiman",
      "id": 142290,
      "node_id": "MDQ6VXNlcjE0MjI5MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/holiman",
      "html_url": "https://github.com/holiman",
      "followers_url": "https://api.github.com/users/holiman/followers",
      "following_url": "https://api.github.com/users/holiman/following{/other_user}",
      "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
      "organizations_url": "https://api.github.com/users/holiman/orgs",
      "repos_url": "https://api.github.com/users/holiman/repos",
      "events_url": "https://api.github.com/users/holiman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/holiman/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-10-20T06:23:25Z",
    "updated_at": "2021-10-20T06:23:25Z",
    "author_association": "MEMBER",
    "body": "Stale, closing this",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/947365378/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
