{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/2313",
  "id": 139416665,
  "node_id": "MDU6SXNzdWUxMzk0MTY2NjU=",
  "number": 2313,
  "title": "Bad block #116525",
  "user": {
    "login": "Aranad",
    "id": 1755922,
    "node_id": "MDQ6VXNlcjE3NTU5MjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1755922?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aranad",
    "html_url": "https://github.com/Aranad",
    "followers_url": "https://api.github.com/users/Aranad/followers",
    "following_url": "https://api.github.com/users/Aranad/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aranad/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aranad/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aranad/subscriptions",
    "organizations_url": "https://api.github.com/users/Aranad/orgs",
    "repos_url": "https://api.github.com/users/Aranad/repos",
    "events_url": "https://api.github.com/users/Aranad/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aranad/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2016-03-08T22:46:15Z",
  "updated_at": "2016-03-09T10:10:20Z",
  "closed_at": "2016-03-09T10:10:16Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I'm trying to run geth but it won't sync, I tried reloading the whole block chain from scratch but still dies at the same block, 116525. I'm running the latest version 1.3.5.\n\nI0308 15:34:54.188672   21792 downloader.go:278] Block synchronisation started\nI0308 15:35:05.612007   21792 chain_manager.go:788] Bad block #116525 (ec46ee8db536b9bfe6c0721c9d98e231c9b4731acf60ae6e74f41645ad0354ac)\nI0308 15:35:05.612036   21792 chain_manager.go:789] gas used error (2625335 / 2625969)\nI0308 15:35:05.612132   21792 downloader.go:254] Synchronisation failed: hash fetching canceled (requested)\n",
  "closed_by": {
    "login": "Aranad",
    "id": 1755922,
    "node_id": "MDQ6VXNlcjE3NTU5MjI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1755922?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aranad",
    "html_url": "https://github.com/Aranad",
    "followers_url": "https://api.github.com/users/Aranad/followers",
    "following_url": "https://api.github.com/users/Aranad/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aranad/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aranad/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aranad/subscriptions",
    "organizations_url": "https://api.github.com/users/Aranad/orgs",
    "repos_url": "https://api.github.com/users/Aranad/repos",
    "events_url": "https://api.github.com/users/Aranad/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aranad/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194170836",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/2313#issuecomment-194170836",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313",
    "id": 194170836,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NDE3MDgzNg==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-09T08:06:39Z",
    "updated_at": "2016-03-09T08:06:39Z",
    "author_association": "MEMBER",
    "body": "Are you sure you're running `1.3.5`? \n- I've just pulled and ran 1.3.5 and it synced just fine past that block.\n- The log `hash fetching canceled (requested)` does not exist in 1.3.5 (it doesn't exist since Novemeber).\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194170836/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194191598",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/2313#issuecomment-194191598",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313",
    "id": 194191598,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NDE5MTU5OA==",
    "user": {
      "login": "Atrides",
      "id": 6382663,
      "node_id": "MDQ6VXNlcjYzODI2NjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6382663?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Atrides",
      "html_url": "https://github.com/Atrides",
      "followers_url": "https://api.github.com/users/Atrides/followers",
      "following_url": "https://api.github.com/users/Atrides/following{/other_user}",
      "gists_url": "https://api.github.com/users/Atrides/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Atrides/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Atrides/subscriptions",
      "organizations_url": "https://api.github.com/users/Atrides/orgs",
      "repos_url": "https://api.github.com/users/Atrides/repos",
      "events_url": "https://api.github.com/users/Atrides/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Atrides/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-09T09:00:56Z",
    "updated_at": "2016-03-09T09:02:39Z",
    "author_association": "NONE",
    "body": "I have the same problem on one node. May be ralated with issue #2305 bacause http://pastebin.com/rP5Re3i8\ninstance: Geth/v1.3.5/linux/go1.5.1\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194191598/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194191935",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/2313#issuecomment-194191935",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313",
    "id": 194191935,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NDE5MTkzNQ==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-09T09:02:31Z",
    "updated_at": "2016-03-09T09:02:31Z",
    "author_association": "MEMBER",
    "body": "@Atrides That is a simple data race. There's a PR open to address it. This issue is different and cannot happen unless you're using a half a year old version of the client.\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194191935/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194221263",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/2313#issuecomment-194221263",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/2313",
    "id": 194221263,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NDIyMTI2Mw==",
    "user": {
      "login": "Aranad",
      "id": 1755922,
      "node_id": "MDQ6VXNlcjE3NTU5MjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1755922?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Aranad",
      "html_url": "https://github.com/Aranad",
      "followers_url": "https://api.github.com/users/Aranad/followers",
      "following_url": "https://api.github.com/users/Aranad/following{/other_user}",
      "gists_url": "https://api.github.com/users/Aranad/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Aranad/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Aranad/subscriptions",
      "organizations_url": "https://api.github.com/users/Aranad/orgs",
      "repos_url": "https://api.github.com/users/Aranad/repos",
      "events_url": "https://api.github.com/users/Aranad/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Aranad/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-09T10:09:17Z",
    "updated_at": "2016-03-09T10:09:17Z",
    "author_association": "NONE",
    "body": "Thanks for pointing that out! I realised I had changed the git branch to 1.3.5 but hadn't run make again, working now :-)\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/194221263/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
