{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/978",
  "id": 76375512,
  "node_id": "MDU6SXNzdWU3NjM3NTUxMg==",
  "number": 978,
  "title": "Synchronisation failed: peer's unknown or unhealthy",
  "user": {
    "login": "avdoshyn",
    "id": 11573326,
    "node_id": "MDQ6VXNlcjExNTczMzI2",
    "avatar_url": "https://avatars.githubusercontent.com/u/11573326?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/avdoshyn",
    "html_url": "https://github.com/avdoshyn",
    "followers_url": "https://api.github.com/users/avdoshyn/followers",
    "following_url": "https://api.github.com/users/avdoshyn/following{/other_user}",
    "gists_url": "https://api.github.com/users/avdoshyn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/avdoshyn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/avdoshyn/subscriptions",
    "organizations_url": "https://api.github.com/users/avdoshyn/orgs",
    "repos_url": "https://api.github.com/users/avdoshyn/repos",
    "events_url": "https://api.github.com/users/avdoshyn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/avdoshyn/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2015-05-14T14:26:57Z",
  "updated_at": "2015-05-15T13:42:56Z",
  "closed_at": "2015-05-15T13:42:56Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "http://prntscr.com/754g68\n\nI0514 16:24:51.652331    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:03.931033    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:10.934434    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:16.017725    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:25.066242    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:26.581329    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:30.211536    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:38.765026    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:39.756082    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:43.206280    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:54.248911    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:25:59.477210    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:26:14.845089    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:26:18.678309    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:26:22.662536    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:26:22.918551    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\nI0514 16:26:26.873777    2248 sync.go:104] Synchronisation failed: peer's unknown or unhealthy\n",
  "closed_by": {
    "login": "karalabe",
    "id": 129561,
    "node_id": "MDQ6VXNlcjEyOTU2MQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/karalabe",
    "html_url": "https://github.com/karalabe",
    "followers_url": "https://api.github.com/users/karalabe/followers",
    "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
    "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
    "organizations_url": "https://api.github.com/users/karalabe/orgs",
    "repos_url": "https://api.github.com/users/karalabe/repos",
    "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/karalabe/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102071419",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/978#issuecomment-102071419",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978",
    "id": 102071419,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwMjA3MTQxOQ==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-14T15:26:28Z",
    "updated_at": "2015-05-14T15:28:30Z",
    "author_association": "MEMBER",
    "body": "Geth version? Number of peers?\n\nEdit: That error is returned when you try to sync with a peer that is foreign to the downloader (i.e. it was already thrown out for some reason). If you have a proper network connection this shouldn't really happen. Does it keep happening if you restart geth?\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102071419/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102104034",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/978#issuecomment-102104034",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978",
    "id": 102104034,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwMjEwNDAzNA==",
    "user": {
      "login": "avdoshyn",
      "id": 11573326,
      "node_id": "MDQ6VXNlcjExNTczMzI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/11573326?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/avdoshyn",
      "html_url": "https://github.com/avdoshyn",
      "followers_url": "https://api.github.com/users/avdoshyn/followers",
      "following_url": "https://api.github.com/users/avdoshyn/following{/other_user}",
      "gists_url": "https://api.github.com/users/avdoshyn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/avdoshyn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/avdoshyn/subscriptions",
      "organizations_url": "https://api.github.com/users/avdoshyn/orgs",
      "repos_url": "https://api.github.com/users/avdoshyn/repos",
      "events_url": "https://api.github.com/users/avdoshyn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/avdoshyn/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-14T17:05:21Z",
    "updated_at": "2015-05-14T17:05:21Z",
    "author_association": "NONE",
    "body": "CPU=4 TOT=6\nGeth-Win 0.9.20\n\n> > Does it keep happening if you restart geth?\n\nnow is ok\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102104034/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102401096",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/978#issuecomment-102401096",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/978",
    "id": 102401096,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwMjQwMTA5Ng==",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-15T13:42:56Z",
    "updated_at": "2015-05-15T13:42:56Z",
    "author_association": "MEMBER",
    "body": "I'm guessing this was only a bad network connection, because of which you tried to pull from the same faulty peer. I'll close this now, but feel free to open a new issue if it reappears. Btw, if it does, please also send the number of peers you have (you can query that if you run the console and type `net` into it).\n",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/102401096/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
