{
  "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
  "repository_url": "https://api.github.com/repos/ChainSafe/lodestar",
  "labels_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423/labels{/name}",
  "comments_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423/comments",
  "events_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423/events",
  "html_url": "https://github.com/ChainSafe/lodestar/issues/3423",
  "id": 1048728787,
  "node_id": "I_kwDOCD5_Gc4-glTT",
  "number": 3423,
  "title": "Bootnode and P2P discovery doesn't work sometimes",
  "user": {
    "login": "skylenet",
    "id": 1500888,
    "node_id": "MDQ6VXNlcjE1MDA4ODg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/skylenet",
    "html_url": "https://github.com/skylenet",
    "followers_url": "https://api.github.com/users/skylenet/followers",
    "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
    "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
    "organizations_url": "https://api.github.com/users/skylenet/orgs",
    "repos_url": "https://api.github.com/users/skylenet/repos",
    "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/skylenet/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 2155825090,
      "node_id": "MDU6TGFiZWwyMTU1ODI1MDkw",
      "url": "https://api.github.com/repos/ChainSafe/lodestar/labels/scope-networking",
      "name": "scope-networking",
      "color": "980043",
      "default": false,
      "description": "All issues related to networking, gossip, and libp2p."
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "tuyennhv",
    "id": 10568965,
    "node_id": "MDQ6VXNlcjEwNTY4OTY1",
    "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tuyennhv",
    "html_url": "https://github.com/tuyennhv",
    "followers_url": "https://api.github.com/users/tuyennhv/followers",
    "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
    "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
    "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
    "repos_url": "https://api.github.com/users/tuyennhv/repos",
    "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 28,
  "created_at": "2021-11-09T15:17:40Z",
  "updated_at": "2022-02-19T10:17:58Z",
  "closed_at": "2022-02-19T10:17:57Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<!--NOTE: -->\r\n<!--- General questions should go to the discord chat instead of the issue tracker.-->\r\n\r\n**Describe the bug**\r\n\r\nI have a private cluster and I'm running multiple lodestar nodes. I've noticed that sometimes the bootnode connectiviy seems to work fine and lodestar gets peers. Other times it just doesn't and nothing else happens. See the following example of 2 nodes, where 1 is working fine and the other isn't discoverying any peers, even though they have the same bootnode configured. \r\n\r\n**Expected behavior**\r\n\r\nBootnode should work, or on failure I should see any logs why it didn't work. \r\n\r\n**Steps to Reproduce**\r\n\r\n<!--Steps to reproduce the behavior:\r\n1. Go to '...'\r\n2. Click on '....'\r\n3. Scroll down to '....'\r\n4. See error\r\n-->\r\n\r\n### Config\r\n\r\nI'm running many lodestar clients with this config. Note that each client has it's own `/data` dir and it's not shared between them.\r\n\r\n```\r\nnode /usr/app/node_modules/.bin/lodestar beacon\r\n--rootDir=/data\r\n--network.discv5.bindAddr=/ip4/0.0.0.0/udp/9000\r\n--network.localMultiaddrs=/ip4/0.0.0.0/tcp/9000\r\n--enr.ip=10.244.6.73\r\n--enr.tcp=9000\r\n--enr.udp=9000\r\n--api.rest.enabled=true\r\n--api.rest.host=0.0.0.0\r\n--api.rest.port=9596\r\n--metrics.enabled=true\r\n--metrics.listenAddr=0.0.0.0\r\n--metrics.serverPort=8008\r\n--genesisStateFile=/data/testnet_spec/genesis.ssz\r\n--paramsFile=/data/testnet_spec/config.yaml\r\n--network.discv5.bootEnrs=enr:-Ly4QPfI8vDLJRr5z14BBEVq1bPq07BhNbCcyftRUhmFf1eWR2Wn_VVnsEelOzYecvJBROTKUsxotWYO3CKPHcmwQIQBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAy95SQAQAQIDSPAAAAAAAAgmlkgnY0gmlwhAr0BsCJc2VjcDI1NmsxoQM-99Lt2OAst8ZF343Up2AGD_dOY1BzO85p2bGjm__AgohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA\r\n--network.connectToDiscv5Bootnodes=true\r\n--eth1.enabled\r\n--eth1.providerUrls=http://geth.ethereum-private.svc.cluster.local:8545\r\n--logLevel=silly\r\n--eth1.depositContractDeployBlock=0\r\n```\r\n\r\n### Working node that was able to discover peers\r\n\r\n\r\n[lodestar_works.log](https://github.com/ChainSafe/lodestar/files/7505862/lodestar_works.log)\r\n\r\n\r\n### Broken node that failed discovering peers\r\n\r\n[lodestar_fail.log](https://github.com/ChainSafe/lodestar/files/7505860/lodestar_fail.log)\r\n\r\n\r\n**Desktop (please complete the following information):**\r\n\r\n- OS: Linux docker container \r\n- Docker image: chainsafe/lodestar:next\r\n- Version:  v0.31.0/master/+93/08dbb215 (git)\r\n",
  "closed_by": {
    "login": "skylenet",
    "id": 1500888,
    "node_id": "MDQ6VXNlcjE1MDA4ODg=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/skylenet",
    "html_url": "https://github.com/skylenet",
    "followers_url": "https://api.github.com/users/skylenet/followers",
    "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
    "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
    "organizations_url": "https://api.github.com/users/skylenet/orgs",
    "repos_url": "https://api.github.com/users/skylenet/repos",
    "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
    "received_events_url": "https://api.github.com/users/skylenet/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964385638",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-964385638",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 964385638,
    "node_id": "IC_kwDOCD5_Gc45e1tm",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-09T17:45:04Z",
    "updated_at": "2021-11-09T17:45:04Z",
    "author_association": "MEMBER",
    "body": "@skylenet Thanks for reporting! Could you detail a bit more the node configuration to be able to recreate locally?\r\n- The bootnode is a Lodestar node?\r\n- How many nodes there are in the network in total during the test?\r\n- How many peers is the bootnode DHT aware of that are in the same network?\r\n\r\nA potential issue causing this is that we only request ENRs from a single bucket to the bootnode, so in tiny network we might not find any ENRs. However the `connectToDiscv5Bootnodes` flag should still land you with one peer",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964385638/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964425421",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-964425421",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 964425421,
    "node_id": "IC_kwDOCD5_Gc45e_bN",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-09T18:35:54Z",
    "updated_at": "2021-11-09T18:37:27Z",
    "author_association": "NONE",
    "body": "Hey @dapplion thanks for looking into this. Here are your answers:\r\n\r\n- 1 ) The bootnode is a lighthouse node (max peers configured to 500)\r\n- 2 & 3):  The network is just starting from scratch. All nodes do wait for the lighthouse bootnode before starting. So the network size depends on the timing that the node happens to connect to the bootnode. Could range from `1` (just the bootnode) to `N-1` (max network size - the node that is connecting). In my case,  `N` is currently around 25 nodes across different clients.\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964425421/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964710698",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-964710698",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 964710698,
    "node_id": "IC_kwDOCD5_Gc45gFEq",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-10T01:59:09Z",
    "updated_at": "2021-11-10T01:59:09Z",
    "author_association": "CONTRIBUTOR",
    "body": "@skylenet I found that lodestar did not receive any discv5 peers, would you mind adding `DEBUG=discv5:service` before your command so that I can see more discv logs? I expect to see some logs like\r\n\r\n```\r\n  discv5:service Sending lookup. Id: 1, Iteration: 1, Node: 2cebc6f01b68e8331be00929f6440bfa4aa71c403524c60c80129ea064be844b +1ms\r\n  discv5:service Sending lookup. Id: 1, Iteration: 1, Node: 03ac675cea6260f833f5ea8d562f5a21e75ca9f7005173504b717887866a7116 +3ms\r\n  discv5:service Sending lookup. Id: 1, Iteration: 1, Node: 2066746905d616b29a21d25b6afa60dee2f3e73ac69484ee25af436252ad8a2a +1ms\r\nNov-10 08:56:08.839 [NETWORK]          info: PeerId 16Uiu2HAmTnbMNfQhbXtkQXjGiFZUVJfYY56VXeARx6cDqiWtsPJW, Multiaddrs /ip4/127.0.0.1/tcp/9000,/ip4/192.168.15.250/tcp/9000\r\nNov-10 08:56:08.840 []                 warn: Low peer count peers=0\r\nNov-10 08:56:08.842 []                 info: Searching peers - peers: 0 - slot: 1666780 (skipped 92) - head: 1666688 0x55a5…943f - finalized: 0xd337…da2c:52082\r\n  discv5:service Sending PING to 03ac675cea6260f833f5ea8d562f5a21e75ca9f7005173504b717887866a7116 +458ms\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/964710698/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965445824",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-965445824",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 965445824,
    "node_id": "IC_kwDOCD5_Gc45i4jA",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-10T15:48:13Z",
    "updated_at": "2021-11-10T16:10:16Z",
    "author_association": "NONE",
    "body": "@tuyennhv thanks for the ENV var, didn't know about that one!  I've added it and collected logs from a working and a broken node again:\r\n- [lodestar_v2_broken.log](https://github.com/ChainSafe/lodestar/files/7514037/lodestar_v2_broken.log)\r\n- [lodestar_v2_working.log](https://github.com/ChainSafe/lodestar/files/7514038/lodestar_v2_working.log)\r\n\r\nI've left it running and every lookup Id shows the same on the failed node: `Sessions is being established, request failed`. Seems like the sessions wasn't totally established and got stuck in a weird state. 1-3 reboots normally help and it establishes the session, but without a reboot it's just stuck in that state.\r\n\r\n```\r\n...\r\n2021-11-10T15:58:54.331Z discv5:service Starting a new lookup. Id: 34\r\n2021-11-10T15:58:54.332Z discv5:service Sending lookup. Id: 34, Iteration: 1, Node: 71becdbc8ccf15794899298b6d11dd0dc6237ca3fc2ea59aa1cf181db6ecb8dd\r\n2021-11-10T15:58:54.333Z discv5:service Sending request to node: 71becdbc8ccf15794899298b6d11dd0dc6237ca3fc2ea59aa1cf181db6ecb8dd failed: error: Session is being established, request failed\r\n...\r\n```\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965445824/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965616011",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-965616011",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 965616011,
    "node_id": "IC_kwDOCD5_Gc45jiGL",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-10T18:19:44Z",
    "updated_at": "2021-11-10T18:19:44Z",
    "author_association": "MEMBER",
    "body": "@wemeetagain Can you take a look at the debug logs too?",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965616011/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965962266",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-965962266",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 965962266,
    "node_id": "IC_kwDOCD5_Gc45k2oa",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-11T03:45:27Z",
    "updated_at": "2021-11-11T03:45:27Z",
    "author_association": "CONTRIBUTOR",
    "body": "@skylenet there are some issues with the session service being timing out and we failed the 1st lookup after 1s, from the 2nd time we got `Sessions is being established, request failed` as you noted. This does not happen with Prater.\r\n\r\ncould you help try again with `DEBUG=discv5:service,discv5:sessionService` so that we have more logs on session services? Thanks.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/965962266/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/966240134",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-966240134",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 966240134,
    "node_id": "IC_kwDOCD5_Gc45l6eG",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-11T11:51:16Z",
    "updated_at": "2021-11-11T11:51:16Z",
    "author_association": "NONE",
    "body": "@tuyennhv some more logs with `DEBUG=discv5:service,discv5:sessionService`\r\n- [lodestar_v3_broke.log](https://github.com/ChainSafe/lodestar/files/7520161/lodestar_v3_broke.log)\r\n- [lodestar_v3_works.log](https://github.com/ChainSafe/lodestar/files/7520163/lodestar_v3_works.log)\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/966240134/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/966793785",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-966793785",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 966793785,
    "node_id": "IC_kwDOCD5_Gc45oBo5",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-12T03:35:07Z",
    "updated_at": "2021-11-12T03:35:07Z",
    "author_association": "CONTRIBUTOR",
    "body": "Thanks @skylenet a lot for the logs.\r\n\r\nHere's how the worked session happens:\r\n1. Lodestar sends FINDNODES request to the boot node\r\n2. No session, lodestar creates random packet and send to the boot node\r\n3. Receive WHOAREYOU request, send back handshake/auth packet\r\n4. Receive NODES response, session is established\r\n\r\nIn the broken session:\r\n+ On the 1st try, lodestar did not receive a WHOAREYOU request and session is deleted\r\n+ On the 2nd try, lodestar did receive WHOAREYOU request and send back handshake/auth packet but then never receive any more packets/messages from the boot node. Session is not deleted so it has the log `Session is being established` all the time and the handshake process wasn't able to recover\r\n\r\nTo proceed with this issue:\r\n1. Seems like lodestar tried to send the 1st FINDNODES messages too early when the transport is not ready\r\n```\r\n2021-11-11T11:44:03.605Z discv5:service Starting discv5 service with node id a94979c6e3449280c849ddfcde174ddadd3cd4db280193d28743aeeef291a3fb\r\n2021-11-11T11:44:03.605Z discv5:sessionService Starting session service with node id a94979c6e3449280c849ddfcde174ddadd3cd4db280193d28743aeeef291a3fb\r\n2021-11-11T11:44:03.611Z discv5:service Starting a new lookup. Id: 1\r\n```\r\n\r\n2. We need to make sure we delete the pending session after some time so that we can start the next session from scratch\r\n3. On the other hand we need to figure out why the bootnode (lighthoue node?) did not accept lodestar auth packet. @skylenet are you able to get the bootnode logs? If you have the log file, I can filter the log myself (not sure if discv5 log available in the boot node as for lodestar, we have to turn on some flags to do that). If not, could you give us some instructions so that we can setup the dev network ourself?\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/966793785/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/967583824",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-967583824",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 967583824,
    "node_id": "IC_kwDOCD5_Gc45rChQ",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-12T21:23:29Z",
    "updated_at": "2021-11-12T21:23:29Z",
    "author_association": "NONE",
    "body": "@tuyennhv thank you for looking into this :) Here are some sample logs from a fresh network that I just spawned up. The lodestar flags kept the same that we've been using on the previous run. The lighthouse node was launched with `--debug-level=trace`: \r\n\r\n## lighthouse \r\n\r\n```sh\r\n# cmdline\r\nlighthouse beacon_node\r\n--datadir=/data\r\n--disable-upnp\r\n--disable-enr-auto-update\r\n--enr-address=10.244.13.252\r\n--enr-tcp-port=9000\r\n--enr-udp-port=9000\r\n--listen-address=0.0.0.0\r\n--port=9000\r\n--discovery-port=9000\r\n--http\r\n--http-address=0.0.0.0\r\n--http-port=5052\r\n--metrics\r\n--metrics-address=0.0.0.0\r\n--metrics-port=5054\r\n--testnet-dir=/data/testnet_spec\r\n--eth1\r\n--eth1-endpoints=http://dshackle.ethereum-private.svc.cluster.local:8545/eth\r\n--target-peers=500\r\n--debug-level=trace\r\n```\r\n\r\n##  lodestar \r\n\r\n```sh\r\n# env vars\r\nDEBUG=discv5:service,discv5:sessionService\r\n# cmdline\r\nnode /usr/app/node_modules/.bin/lodestar beacon\r\n--rootDir=/data\r\n--network.discv5.bindAddr=/ip4/0.0.0.0/udp/9000\r\n--network.localMultiaddrs=/ip4/0.0.0.0/tcp/9000\r\n--enr.ip=10.244.10.81\r\n--enr.tcp=9000\r\n--enr.udp=9000\r\n--api.rest.enabled=true\r\n--api.rest.host=0.0.0.0\r\n--api.rest.port=9596\r\n--metrics.enabled=true\r\n--metrics.listenAddr=0.0.0.0\r\n--metrics.serverPort=8008\r\n--genesisStateFile=/data/testnet_spec/genesis.ssz\r\n--paramsFile=/data/testnet_spec/config.yaml\r\n--network.discv5.bootEnrs=enr:-Ly4QFFuVbzqSau0O65t_DuIuM0HrJ8ZrcjTmuyqqutRQGjdC3bbj2y4rxL2blRYcE3LWGyZVf7JCang344BBXWse6MBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAy95SQAQAQIDSPAAAAAAAAgmlkgnY0gmlwhAr0DfyJc2VjcDI1NmsxoQOjH7_20zVhSlb17Rfg6EBkfayyBguzK66WGjZGUBs_n4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA\r\n--network.connectToDiscv5Bootnodes=true\r\n--eth1.enabled\r\n--eth1.providerUrls=http://dshackle.ethereum-private.svc.cluster.local:8545/eth\r\n--logLevel=silly\r\n--eth1.depositContractDeployBlock=0\r\n```\r\n\r\n## Logs\r\n\r\n- [lighthouse-bootnode.log](https://github.com/ChainSafe/lodestar/files/7530450/lighthouse-bootnode.log)\r\n- [lodestar-beacon_failed.log](https://github.com/ChainSafe/lodestar/files/7530451/lodestar-beacon_failed.log)\r\n- [lodestar-beacon_worked.log](https://github.com/ChainSafe/lodestar/files/7530452/lodestar-beacon_worked.log)\r\n\r\n\r\nThe whole code to launch this is open source and I'm actively working on it atm. It depends on kubernetes: https://github.com/skylenet/ethereum-helm-charts/pull/27 \r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/967583824/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/968847195",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-968847195",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 968847195,
    "node_id": "IC_kwDOCD5_Gc45v29b",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-15T12:08:47Z",
    "updated_at": "2021-11-15T12:09:57Z",
    "author_association": "CONTRIBUTOR",
    "body": "Thanks @skylenet for the log. It seems the `--debug-level=trace` flag of lighthouse does not help as discv5 is on a lower layer, I could not find any useful log there (we could deep dive into it a little bit if the below does not work).\r\n\r\nWe've just had a fix not to start discv5 on the 1st hearbeat, could you give that a try (by pulling our latest master or our latest docker image)? If you go with `DEBUG=discv5:service,discv5:sessionService`, the log should look something like:\r\n\r\n```\r\n021-11-15T10:10:51.530Z discv5:service Starting discv5 service with node id 5ba50119c3f282470441414915f897f587c1fb48ac2bdaef82039a9dc8053038\r\n2021-11-15T10:10:51.531Z discv5:sessionService Starting session service with node id 5ba50119c3f282470441414915f897f587c1fb48ac2bdaef82039a9dc8053038\r\n\r\n// notice that the below happens after 30s\r\n\r\n2021-11-15T10:11:21.539Z discv5:service Starting a new lookup. Id: 1\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/968847195/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/968861236",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-968861236",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 968861236,
    "node_id": "IC_kwDOCD5_Gc45v6Y0",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-15T12:25:46Z",
    "updated_at": "2021-11-15T12:25:46Z",
    "author_association": "NONE",
    "body": "@tuyennhv I've just tried it with the recent `Version: v0.32.0/master/+2/0f5ee0e5 (git)` and all my lodestar nodes were able to find peers now! :+1: :tada: ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/968861236/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/969128100",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-969128100",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 969128100,
    "node_id": "IC_kwDOCD5_Gc45w7ik",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-15T17:14:01Z",
    "updated_at": "2021-11-15T17:14:01Z",
    "author_association": "MEMBER",
    "body": "@wemeetagain I think we could add a condition that when contacting a node that returns 0 results we could just request all the buckets. If that's dangerous we could limit that to initial bootnodes queries only",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/969128100/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/969352961",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-969352961",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 969352961,
    "node_id": "IC_kwDOCD5_Gc45xycB",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-15T21:48:15Z",
    "updated_at": "2021-11-15T21:48:15Z",
    "author_association": "NONE",
    "body": "@tuyennhv @dapplion err.. I think the problem might still be around. Just gave it another try and I'm seeing nodes hanging again. I'll provide you with some logs in a couple of hours. ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/969352961/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970297324",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-970297324",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 970297324,
    "node_id": "IC_kwDOCD5_Gc451Y_s",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-16T13:55:21Z",
    "updated_at": "2021-11-16T13:55:21Z",
    "author_association": "NONE",
    "body": "@tuyennhv  here we go:  I just started 6 lodestar nodes from scratch and here are all of their logs (2/6 didn't make it):\r\n\r\n- [lodestar-0.log](https://github.com/ChainSafe/lodestar/files/7546818/lodestar-0.log)\r\n- [lodestar-1.log](https://github.com/ChainSafe/lodestar/files/7546819/lodestar-1.log)\r\n- [lodestar-2.log](https://github.com/ChainSafe/lodestar/files/7546820/lodestar-2.log)\r\n- [lodestar-3.log](https://github.com/ChainSafe/lodestar/files/7546821/lodestar-3.log)  Failed\r\n- [lodestar-4.log](https://github.com/ChainSafe/lodestar/files/7546822/lodestar-4.log)  Failed\r\n- [lodestar-5.log](https://github.com/ChainSafe/lodestar/files/7546823/lodestar-5.log)\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970297324/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970392523",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-970392523",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 970392523,
    "node_id": "IC_kwDOCD5_Gc451wPL",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-16T15:34:47Z",
    "updated_at": "2021-11-16T15:34:47Z",
    "author_association": "CONTRIBUTOR",
    "body": "thanks @skylenet , this time it does show that we only issue FINDNODES 30s after we start discv5, and it's still an issue. Again, lodestar node sent authentication packet but lighthouse did not response.\r\n\r\nwe are trying to set up the devnet ourself. In the mean time, could you try again with this flag `RUST_LOG=discv5=trace` added to lighthouse node? Thank you so much!",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970392523/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970415284",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-970415284",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 970415284,
    "node_id": "IC_kwDOCD5_Gc4511y0",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-16T15:58:54Z",
    "updated_at": "2021-11-16T17:26:25Z",
    "author_association": "NONE",
    "body": "@tuyennhv  I've added `RUST_LOG=discv5=trace` to the lighthouse bootnode. I'm not sure if it made a difference to the lighthouse logs, but I double checked that the ENV var was set (by checking `/proc/1/environ` on the lighthouse container):\r\n\r\n- [lighthouse-bootnode-0.log](https://github.com/ChainSafe/lodestar/files/7547897/lighthouse-bootnode-0.log)\r\n- [lodestar-0.log](https://github.com/ChainSafe/lodestar/files/7547898/lodestar-0.log)\r\n- [lodestar-1.log](https://github.com/ChainSafe/lodestar/files/7547899/lodestar-1.log)\r\n- [lodestar-2.log](https://github.com/ChainSafe/lodestar/files/7547901/lodestar-2.log)\r\n- [lodestar-3.log](https://github.com/ChainSafe/lodestar/files/7547902/lodestar-3.log)\r\n- [lodestar-4.log](https://github.com/ChainSafe/lodestar/files/7547903/lodestar-4.log)\r\n- [lodestar-5.log](https://github.com/ChainSafe/lodestar/files/7547904/lodestar-5.log) Failed\r\n\r\nFYI: I also have other lighthouse nodes, prysm, nimbus and teku running on the same network and lodestar is currently the only one with this behavior. \r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/970415284/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/972753798",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-972753798",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 972753798,
    "node_id": "IC_kwDOCD5_Gc45-wuG",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-18T10:52:33Z",
    "updated_at": "2021-11-18T10:52:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "thanks @skylenet for the log, actually I don't see any lighthouse discv5 logs. Could you please also try `RUST_LOG=\"discv5=debug\"` and `RUST_LOG=discv5=debug` (without the double quote?). I'm sorry that I can't find a quick/easy way to set up the test network to reproduce the issue myself.\r\n\r\nI double checked with lighthouse and they confirm that's really the only thing to get discv5 log, here's the repo https://github.com/sigp/discv5 , I found that there's a lot of log there for example https://github.com/sigp/discv5/blob/06e8af6e80bb4cacb909ff8a4637187d7bf9f7df/src/service.rs#L1010",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/972753798/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974272768",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-974272768",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 974272768,
    "node_id": "IC_kwDOCD5_Gc46EjkA",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-19T17:37:59Z",
    "updated_at": "2021-11-19T17:37:59Z",
    "author_association": "NONE",
    "body": "@tuyennhv I found out that I was missing the `-l` flag on lighthouse which based on `--help`: *\"Enables environment logging giving access to sub-protocol logs such as discv5 and libp2p\"*. That together with `RUST_LOG=discv5=trace` worked fine now :) \r\n\r\nNew logs:\r\n- [1637342988-lighthouse-bootnode-0.log](https://github.com/ChainSafe/lodestar/files/7571942/1637342988-lighthouse-bootnode-0.log)\r\n- [1637342988-lodestar-0.log](https://github.com/ChainSafe/lodestar/files/7571943/1637342988-lodestar-0.log)\r\n- [1637342988-lodestar-1.log](https://github.com/ChainSafe/lodestar/files/7571944/1637342988-lodestar-1.log) failed \r\n- [1637342988-lodestar-2.log](https://github.com/ChainSafe/lodestar/files/7571945/1637342988-lodestar-2.log)\r\n- [1637342988-lodestar-3.log](https://github.com/ChainSafe/lodestar/files/7571947/1637342988-lodestar-3.log)\r\n- [1637342988-lodestar-4.log](https://github.com/ChainSafe/lodestar/files/7571948/1637342988-lodestar-4.log)\r\n- [1637342988-lodestar-5.log](https://github.com/ChainSafe/lodestar/files/7571949/1637342988-lodestar-5.log)\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974272768/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974741774",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-974741774",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 974741774,
    "node_id": "IC_kwDOCD5_Gc46GWEO",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-21T02:00:10Z",
    "updated_at": "2021-11-21T02:00:10Z",
    "author_association": "CONTRIBUTOR",
    "body": "Looks like this is something related to rate limiting at lighthoue side.\r\n\r\n+ lodestar log\r\n\r\n```\r\n2021-11-19T17:28:35.644Z discv5:sessionService No session established, sending a random packet to: 51e817c3af7ac0508de69b3049c1396f58a94d42c60c41b11328d9c7e6b1b948 on /ip4/10.244.10.227/udp/9000\r\n2021-11-19T17:28:35.652Z discv5:sessionService Received a WHOAREYOU packet. source: /ip4/10.244.10.227/udp/9000\r\n2021-11-19T17:28:35.657Z discv5:sessionService Sending authentication message: { type: 3, id: 5146642605715401423n, distances: [ 256, 255, 254 ] } to node: 51e817c3af7ac0508de69b3049c1396f58a94d42c60c41b11328d9c7e6b1b948 on /ip4/10.244.10.227/udp/9000\r\nNov-19 17:28:36.001 []                 \u001B[32minfo\u001B[39m: Searching peers - peers: 0 - slot: -13 - head: 0 0xbcea…9dc3 - finalized: 0x0000…0000:0\r\n2021-11-19T17:28:36.647Z discv5:service Lookup Id: 1 finished, 0 total found\r\n```\r\n\r\n+ lighthouse log\r\n```\r\n[2021-11-19T17:28:35Z TRACE discv5::handler] Received a message without a session. Node: 0x044e..db03, addr: 10.244.15.4:9000 \r\n[2021-11-19T17:28:35Z TRACE discv5::handler] Requesting a WHOAREYOU packet to be sent. \r\n[2021-11-19T17:28:35Z DEBUG discv5::service] NodeId unknown, requesting ENR. Node: 0x044e..db03, addr: 10.244.15.4:9000 \r\n[2021-11-19T17:28:35Z DEBUG discv5::handler] Sending WHOAREYOU to Node: 0x044e..db03, addr: 10.244.15.4:9000 \r\n[2021-11-19T17:28:35Z DEBUG discv5::socket::filter] Dropped unsolicited packet from RPC limit: 10.244.15.4 \r\n[2021-11-19T17:28:35Z TRACE discv5::socket::recv] Packet filtered from source: 10.244.15.4:9000 \r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974741774/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974745844",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-974745844",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 974745844,
    "node_id": "IC_kwDOCD5_Gc46GXD0",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-21T02:46:46Z",
    "updated_at": "2021-11-21T02:46:46Z",
    "author_association": "CONTRIBUTOR",
    "body": "@skylenet I just talk to Lighthouse team, we can disable rate limiting with `--disable-packet-filter`, could you give it a try? This does not seem like a code issue at lodestar discv5 if rate limiting is an issue.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/974745844/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/976362073",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-976362073",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 976362073,
    "node_id": "IC_kwDOCD5_Gc46MhpZ",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-23T10:07:51Z",
    "updated_at": "2021-11-23T10:07:51Z",
    "author_association": "MEMBER",
    "body": "@tuyennhv Our current discv5 implementation sends a ton of FINDNODE requests to a node. During a single random node lookup about 501 through 1 minute. Could this trigger the rate limiting of Lighthouse? How many FINDNODE requests do they allow for time unit?",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/976362073/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977630889",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-977630889",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 977630889,
    "node_id": "IC_kwDOCD5_Gc46RXap",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-24T08:12:03Z",
    "updated_at": "2021-11-24T08:12:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "@dapplion  this log `Dropped unsolicited packet from RPC limit` shows that the request failed due to the total limit, not node limit or ip limit https://github.com/sigp/discv5/blob/06e8af6e80bb4cacb909ff8a4637187d7bf9f7df/src/socket/filter/mod.rs#L134 , also this failed right after we start the node at the 1st/2nd request, we haven't abused the boot node yet\r\n\r\nthis shows the rate limit params per request \r\n(udp request, not FINDNODE request) https://github.com/sigp/discv5/blob/06e8af6e80bb4cacb909ff8a4637187d7bf9f7df/src/config.rs#L104\r\n\r\n+ total: 10 per sec\r\n+ per node: 8 per sec\r\n+ per ip: 9 per sec\r\n\r\n@skylenet also one thing we can try is not to start all lodestar nodes at the same time, just one by one, in order to get through this total rate limit issue",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977630889/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977725771",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-977725771",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 977725771,
    "node_id": "IC_kwDOCD5_Gc46RulL",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-24T10:08:55Z",
    "updated_at": "2021-11-24T10:08:55Z",
    "author_association": "MEMBER",
    "body": "@tuyennhv @wemeetagain  Tho our node should be able to recover from this, realize that the handshake is not completed and start over right?",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977725771/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977730694",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-977730694",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 977730694,
    "node_id": "IC_kwDOCD5_Gc46RvyG",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-24T10:14:40Z",
    "updated_at": "2021-11-24T10:14:40Z",
    "author_association": "NONE",
    "body": "@tuyennhv  Disabling the rate limiting on lighthouse or starting the lodestar nodes slowly one of the other would kinda work as a workaround for my case, but I think that client should be able to recover from this situation.\r\n\r\n> @tuyennhv @wemeetagain Tho our node should be able to recover from this, realize that the handshake is not completed and start over right?\r\n\r\nI agree with this. And this is also what happens on other clients. They eventually are able to connect without me having to reboot them manually. Lodestar seems to be the only one right now that gets the session stuck and never manages to connect if lighthouse throttles it.   ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/977730694/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/982208366",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-982208366",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 982208366,
    "node_id": "IC_kwDOCD5_Gc46i09u",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-11-30T02:00:36Z",
    "updated_at": "2021-11-30T02:00:36Z",
    "author_association": "CONTRIBUTOR",
    "body": "@skylenet lodestar is reworking on discv5 https://github.com/ChainSafe/discv5/pull/155 , I think this is a good test for that PR @wemeetagain ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/982208366/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1029832789",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-1029832789",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 1029832789,
    "node_id": "IC_kwDOCD5_Gc49YgBV",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-02-04T10:14:58Z",
    "updated_at": "2022-02-04T10:14:58Z",
    "author_association": "MEMBER",
    "body": "New discv5 version from https://github.com/ChainSafe/discv5/pull/155 has been merged to Lodestar master. Could you please @tuyennhv check if the issue is still happening?",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1029832789/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1034394302",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-1034394302",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 1034394302,
    "node_id": "IC_kwDOCD5_Gc49p5q-",
    "user": {
      "login": "tuyennhv",
      "id": 10568965,
      "node_id": "MDQ6VXNlcjEwNTY4OTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10568965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tuyennhv",
      "html_url": "https://github.com/tuyennhv",
      "followers_url": "https://api.github.com/users/tuyennhv/followers",
      "following_url": "https://api.github.com/users/tuyennhv/following{/other_user}",
      "gists_url": "https://api.github.com/users/tuyennhv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tuyennhv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tuyennhv/subscriptions",
      "organizations_url": "https://api.github.com/users/tuyennhv/orgs",
      "repos_url": "https://api.github.com/users/tuyennhv/repos",
      "events_url": "https://api.github.com/users/tuyennhv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tuyennhv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-02-10T01:36:03Z",
    "updated_at": "2022-02-10T01:36:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "> New discv5 version from [ChainSafe/discv5#155](https://github.com/ChainSafe/discv5/pull/155) has been merged to Lodestar master. Could you please @tuyennhv check if the issue is still happening?\r\n\r\nI'm not able to reproduce the issue, @skylenet could you help us verify this again? Thanks.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1034394302/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1045984669",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-1045984669",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/3423",
    "id": 1045984669,
    "node_id": "IC_kwDOCD5_Gc4-WHWd",
    "user": {
      "login": "skylenet",
      "id": 1500888,
      "node_id": "MDQ6VXNlcjE1MDA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1500888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/skylenet",
      "html_url": "https://github.com/skylenet",
      "followers_url": "https://api.github.com/users/skylenet/followers",
      "following_url": "https://api.github.com/users/skylenet/following{/other_user}",
      "gists_url": "https://api.github.com/users/skylenet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/skylenet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/skylenet/subscriptions",
      "organizations_url": "https://api.github.com/users/skylenet/orgs",
      "repos_url": "https://api.github.com/users/skylenet/repos",
      "events_url": "https://api.github.com/users/skylenet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/skylenet/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-02-19T10:17:57Z",
    "updated_at": "2022-02-19T10:17:57Z",
    "author_association": "NONE",
    "body": "I think we can close this one. I haven't noticed this any more. Thanks guys! :100: :tada: ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1045984669/reactions",
      "total_count": 3,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 3,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
