{
  "url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961",
  "repository_url": "https://api.github.com/repos/foundry-rs/foundry",
  "labels_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961/labels{/name}",
  "comments_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961/comments",
  "events_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961/events",
  "html_url": "https://github.com/foundry-rs/foundry/issues/4961",
  "id": 1713775985,
  "node_id": "I_kwDOGBlvNc5mJiVx",
  "number": 4961,
  "title": "cannot run anvil behind nginx-proxy",
  "user": {
    "login": "DegenComedian",
    "id": 111272057,
    "node_id": "U_kgDOBqHgeQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/111272057?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DegenComedian",
    "html_url": "https://github.com/DegenComedian",
    "followers_url": "https://api.github.com/users/DegenComedian/followers",
    "following_url": "https://api.github.com/users/DegenComedian/following{/other_user}",
    "gists_url": "https://api.github.com/users/DegenComedian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DegenComedian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DegenComedian/subscriptions",
    "organizations_url": "https://api.github.com/users/DegenComedian/orgs",
    "repos_url": "https://api.github.com/users/DegenComedian/repos",
    "events_url": "https://api.github.com/users/DegenComedian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DegenComedian/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 3334394228,
      "node_id": "MDU6TGFiZWwzMzM0Mzk0MjI4",
      "url": "https://api.github.com/repos/foundry-rs/foundry/labels/T-bug",
      "name": "T-bug",
      "color": "d73a4a",
      "default": false,
      "description": "Type: bug"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2023-05-17T12:15:54Z",
  "updated_at": "2023-05-18T20:00:12Z",
  "closed_at": "2023-05-18T20:00:12Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "### Component\r\n\r\nAnvil\r\n\r\n### Have you ensured that all of these are up to date?\r\n\r\n- [X] Foundry\r\n- [X] Foundryup\r\n\r\n### What version of Foundry are you on?\r\n\r\nforge 0.2.0 (58a2729 2023-05-15T07:53:59.692600892Z)\r\n\r\n### What command(s) is the bug in?\r\n\r\nanvil\r\n\r\n### Operating System\r\n\r\nLinux\r\n\r\n### Describe the bug\r\n\r\nHi, I am trying to run an `anvil` avalanche local fork docker instance behind an [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy).\r\n\r\nWhile I can reach every service of my docker-compose setup, I cannot do this with anvil. Somehow anvil seems to not like some of the nginx configuration automatically done for it but I cannot figure out the problem.\r\n\r\nDockerfile\r\n```Dockerfile\r\n# Use the latest foundry image\r\nFROM ghcr.io/foundry-rs/foundry\r\nWORKDIR /app\r\n\r\nCMD [\"anvil\", \"--host\", \"0.0.0.0\", \"--port\", \"8545\", \"--fork-url\", \"https://api.avax.network/ext/bc/C/rpc\", \"--fork-block-number\", \"30076731\", \"--retries\", \"30\"]\r\n\r\n```\r\n\r\ndocker-compose.yaml\r\n```yaml\r\nversion: '2'\r\n\r\nservices:\r\n\r\n  nginx-proxy:\r\n    image: nginxproxy/nginx-proxy\r\n    ports:\r\n      - \"80:80\"\r\n    volumes:\r\n      - /var/run/docker.sock:/tmp/docker.sock:ro\r\n    environment:\r\n      - TRUST_DOWNSTREAM_PROXY=true\r\n\r\n  anvil-blockchain: \r\n    build:\r\n      context: ./\r\n      dockerfile: Dockerfile\r\n    restart: always\r\n    environment:\r\n      - VIRTUAL_HOST=anvil-avax-mainnet-fork.example.com\r\n      - VIRTUAL_PORT=8545 \r\n    expose:\r\n      - \"8545\"\r\n\r\n  whoami:\r\n    image: jwilder/whoami\r\n    expose:\r\n      - \"8000\"\r\n    environment:\r\n      - VIRTUAL_HOST=whoami.local\r\n      - VIRTUAL_PORT=8000\r\n```\r\n\r\nnow lets run this setup\r\n\r\n```bash\r\n$ docker-compose build\r\n$ docker-compose up -d\r\n```\r\n\r\nproxying the `whomai` service works flawlessly:\r\n\r\n```bash\r\n$ curl -H \"Host: whoami.local\" http://127.0.0.1/\r\nI'm b801b1dca788\r\n```\r\n\r\ntrying to access the anvil blockchain from within the container works fine:\r\n\r\n```bash\r\n$ docker exec -it $(docker ps | grep anvil-blockchain | awk '{print $1}') \\\r\nwget -qO- --header=\"Host: anvil-avax-mainnet-fork.example.com\" \\\r\n--header=\"content-type: application/json;\" \\\r\n--post-data='{ \"jsonrpc\":\"2.0\", \"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' \\\r\nhttp://127.0.0.1:8545/\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"0x0\"}% \r\n```\r\n\r\nwhereas when I try to access the anvil local blockchain over the proxy, I get an `502 Bad Gateway`\r\n\r\n```bash\r\n$ curl -H \"Host: anvil-avax-mainnet-fork.example.com\" \\\r\n--request POST \\\r\n--header 'content-type:application/json;' \\\r\n--data '{ \"jsonrpc\":\"2.0\", \"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' \\\r\nhttp://127.0.0.1/\r\n\r\n[..]\r\n<head><title>502 Bad Gateway</title></head>\r\n[..]\r\n```\r\n\r\ntherefore I think its a nginx problem.\r\n\r\nnginx log shows the following problem\r\n\r\n```bash\r\n$ docker-compose logs\r\n[..]\r\nnginx.1     | 2023/05/17 12:05:17 [error] 104#104: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: anvil-avax-mainnet-fork.example.com, request: \"GET / HTTP/1.1\", upstream: \"http://172.20.0.2:8545/\", host: \"anvil-avax-mainnet-fork.example.com\"\r\nnginx.1     | anvil-avax-mainnet-fork.example.com 172.20.0.1 - - [17/May/2023:12:05:17 +0000] \"GET / HTTP/1.1\" 502 157 \"-\" \"curl/7.71.1\" \"172.20.0.2:8545\"\r\n[..]\r\n```\r\n\r\nyou can see the actual nginx configuration using\r\n\r\n```bash\r\n$ docker exec -it $(docker ps | grep nginx-proxy | awk '{print $1}') nginx -T\r\n\r\n[...]\r\n# anvil-avax-mainnet-fork.example.com/\r\nupstream anvil-avax-mainnet-fork.example.com {\r\n    # Container: test_anvil-blockchain_1\r\n    #     networks:\r\n    #         test_default (reachable)\r\n    #     IP address: 172.20.0.2\r\n    #     exposed ports: 8545/tcp\r\n    #     default port: 8545\r\n    #     using port: 8545\r\n    server 172.20.0.2:8545;\r\n}\r\nserver {\r\n    server_name anvil-avax-mainnet-fork.example.com;\r\n    access_log /var/log/nginx/access.log vhost;\r\n    listen 80 ;\r\n    listen 443 ssl http2 ;\r\n    # No certificate found for this vhost, so force nginx to emit a TLS error if\r\n    # the client connects via https.\r\n    ssl_ciphers aNULL;\r\n    set $empty \"\";\r\n    ssl_certificate data:$empty;\r\n    ssl_certificate_key data:$empty;\r\n    if ($https) {\r\n        return 444;\r\n    }\r\n    location / {\r\n        proxy_pass http://anvil-avax-mainnet-fork.example.com;\r\n        set $upstream_keepalive false;\r\n    }\r\n}\r\n[...]\r\n```\r\n.\r\nDoes anybody knows which nginx configuration could be problematic here?\r\n\r\n\r\n\r\n\r\n",
  "closed_by": {
    "login": "DegenComedian",
    "id": 111272057,
    "node_id": "U_kgDOBqHgeQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/111272057?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DegenComedian",
    "html_url": "https://github.com/DegenComedian",
    "followers_url": "https://api.github.com/users/DegenComedian/followers",
    "following_url": "https://api.github.com/users/DegenComedian/following{/other_user}",
    "gists_url": "https://api.github.com/users/DegenComedian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DegenComedian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DegenComedian/subscriptions",
    "organizations_url": "https://api.github.com/users/DegenComedian/orgs",
    "repos_url": "https://api.github.com/users/DegenComedian/repos",
    "events_url": "https://api.github.com/users/DegenComedian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DegenComedian/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1551295456",
    "html_url": "https://github.com/foundry-rs/foundry/issues/4961#issuecomment-1551295456",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961",
    "id": 1551295456,
    "node_id": "IC_kwDOGBlvNc5cduPg",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-17T12:22:43Z",
    "updated_at": "2023-05-17T12:22:43Z",
    "author_association": "MEMBER",
    "body": "> request: \"GET / HTTP/1.1\", upstream: \"http://172.20.0.2:8545/\"\r\n\r\nhmm, this should be a POST?",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1551295456/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1551302923",
    "html_url": "https://github.com/foundry-rs/foundry/issues/4961#issuecomment-1551302923",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961",
    "id": 1551302923,
    "node_id": "IC_kwDOGBlvNc5cdwEL",
    "user": {
      "login": "DegenComedian",
      "id": 111272057,
      "node_id": "U_kgDOBqHgeQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/111272057?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DegenComedian",
      "html_url": "https://github.com/DegenComedian",
      "followers_url": "https://api.github.com/users/DegenComedian/followers",
      "following_url": "https://api.github.com/users/DegenComedian/following{/other_user}",
      "gists_url": "https://api.github.com/users/DegenComedian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DegenComedian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DegenComedian/subscriptions",
      "organizations_url": "https://api.github.com/users/DegenComedian/orgs",
      "repos_url": "https://api.github.com/users/DegenComedian/repos",
      "events_url": "https://api.github.com/users/DegenComedian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DegenComedian/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-17T12:28:00Z",
    "updated_at": "2023-05-17T12:28:50Z",
    "author_association": "NONE",
    "body": "sorry, the output posted did not match the curl example I used. It was from another `curl` I tried using GET. Here is the result from the POST.\r\n\r\n```bash\r\nnginx.1     | 2023/05/17 12:26:45 [error] 110#110: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: anvil-avax-mainnet-fork.example.com, request: \"POST / HTTP/1.1\", upstream: \"http://172.20.0.2:8545/\", host: \"anvil-avax-mainnet-fork.example.com\"\r\nnginx.1     | anvil-avax-mainnet-fork.example.com 172.20.0.1 - - [17/May/2023:12:26:45 +0000] \"POST / HTTP/1.1\" 502 157 \"-\" \"curl/7.71.1\" \"172.20.0.2:8545\"\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1551302923/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1553576616",
    "html_url": "https://github.com/foundry-rs/foundry/issues/4961#issuecomment-1553576616",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/4961",
    "id": 1553576616,
    "node_id": "IC_kwDOGBlvNc5cmbKo",
    "user": {
      "login": "DegenComedian",
      "id": 111272057,
      "node_id": "U_kgDOBqHgeQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/111272057?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DegenComedian",
      "html_url": "https://github.com/DegenComedian",
      "followers_url": "https://api.github.com/users/DegenComedian/followers",
      "following_url": "https://api.github.com/users/DegenComedian/following{/other_user}",
      "gists_url": "https://api.github.com/users/DegenComedian/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DegenComedian/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DegenComedian/subscriptions",
      "organizations_url": "https://api.github.com/users/DegenComedian/orgs",
      "repos_url": "https://api.github.com/users/DegenComedian/repos",
      "events_url": "https://api.github.com/users/DegenComedian/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DegenComedian/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-18T20:00:12Z",
    "updated_at": "2023-05-18T20:00:12Z",
    "author_association": "NONE",
    "body": "Got it resolved. \r\nIn my Dockerfile I used `CMD` which did not respect my parameters to anvil. It was starting anvil without any cli parameters so it did not change the host to `0.0.0.0`. Therefore it did not listen on all interfaces so nginx did not get through my anvil backend.\r\nAfter changing to `ENTRYPOINT` all parameters have been correctly applied and everything is working well.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1553576616/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
