{
  "url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890",
  "repository_url": "https://api.github.com/repos/foundry-rs/foundry",
  "labels_url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890/labels{/name}",
  "comments_url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890/comments",
  "events_url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890/events",
  "html_url": "https://github.com/foundry-rs/foundry/issues/5890",
  "id": 1910767459,
  "node_id": "I_kwDOGBlvNc5x4_9j",
  "number": 5890,
  "title": "Unknown Application Panicked Error",
  "user": {
    "login": "kevinsslin",
    "id": 86810837,
    "node_id": "MDQ6VXNlcjg2ODEwODM3",
    "avatar_url": "https://avatars.githubusercontent.com/u/86810837?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kevinsslin",
    "html_url": "https://github.com/kevinsslin",
    "followers_url": "https://api.github.com/users/kevinsslin/followers",
    "following_url": "https://api.github.com/users/kevinsslin/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevinsslin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevinsslin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevinsslin/subscriptions",
    "organizations_url": "https://api.github.com/users/kevinsslin/orgs",
    "repos_url": "https://api.github.com/users/kevinsslin/repos",
    "events_url": "https://api.github.com/users/kevinsslin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevinsslin/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 3334394228,
      "node_id": "MDU6TGFiZWwzMzM0Mzk0MjI4",
      "url": "https://api.github.com/repos/foundry-rs/foundry/labels/T-bug",
      "name": "T-bug",
      "color": "d73a4a",
      "default": false,
      "description": "Type: bug"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2023-09-25T06:31:06Z",
  "updated_at": "2023-09-25T06:38:43Z",
  "closed_at": "2023-09-25T06:38:43Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "### Component\r\n\r\nForge\r\n\r\n### Have you ensured that all of these are up to date?\r\n\r\n- [X] Foundry\r\n- [X] Foundryup\r\n\r\n### What version of Foundry are you on?\r\n\r\nforge 0.2.0 (ec3f9bd 2023-09-19T13:46:42.143604000Z)\r\n\r\n### What command(s) is the bug in?\r\n\r\nforge build\r\n\r\n### Operating System\r\n\r\nmacOS (Apple Silicon)\r\n\r\n### Describe the bug\r\n\r\nWhen I trying to use any command related to forge, I'll get the below message.\r\n\r\n\r\nThe application panicked (crashed).\r\nMessage:  byte index 22 is not a char boundary; it is inside 'π' (bytes 21..23) of `56 |         externalπ`\r\nLocation: /Users/runner/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/4b5e08c/ethers-solc/src/artifacts/mod.rs:2123\r\n\r\nThis is a bug. Consider reporting it at https://github.com/foundry-rs/foundry\r\n\r\nBacktrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.\r\nRun with RUST_BACKTRACE=full to include source snippets.\r\n[1]    31913 abort      forge build\r\n",
  "closed_by": {
    "login": "kevinsslin",
    "id": 86810837,
    "node_id": "MDQ6VXNlcjg2ODEwODM3",
    "avatar_url": "https://avatars.githubusercontent.com/u/86810837?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kevinsslin",
    "html_url": "https://github.com/kevinsslin",
    "followers_url": "https://api.github.com/users/kevinsslin/followers",
    "following_url": "https://api.github.com/users/kevinsslin/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevinsslin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevinsslin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevinsslin/subscriptions",
    "organizations_url": "https://api.github.com/users/kevinsslin/orgs",
    "repos_url": "https://api.github.com/users/kevinsslin/repos",
    "events_url": "https://api.github.com/users/kevinsslin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevinsslin/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/foundry-rs/foundry/issues/5890/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[

]
